initrd: use tpmx extend wrapper
Board specific scripts (ie t430-flash) have not been modified.

Signed-off-by: Cody Ho <codyho@stanford.edu>

diff --git a/initrd/bin/cbfs-init b/initrd/bin/cbfs-init
--- a/initrd/bin/cbfs-init
+++ b/initrd/bin/cbfs-init
@@ -18,13 +18,12 @@ for cbfsname in `echo $cbfsfiles`; do
 		|| die "$filename: mkdir failed"
 		cbfs -t 50 -r $cbfsname > "$filename" \
 		|| die "$filename: cbfs file read failed"
-		if [ "$CONFIG_TPM" = "y" ]; then
-			TMPFILE=/tmp/cbfs.$$
-			echo "$filename" > $TMPFILE
-			cat $filename >> $TMPFILE
-			tpm extend -ix "$CONFIG_PCR" -if $TMPFILE \
-			|| die "$filename: tpm extend failed"
-		fi
+
+		TMPFILE=/tmp/cbfs.$$
+		echo "$filename" > $TMPFILE
+		cat $filename >> $TMPFILE
+		tpmx extend "$TMPFILE" "$CONFIG_PCR"  \
+		|| die "$filename: tpm extend failed"
 	fi
 done
 
diff --git a/initrd/bin/uefi-init b/initrd/bin/uefi-init
--- a/initrd/bin/uefi-init
+++ b/initrd/bin/uefi-init
@@ -18,10 +18,8 @@ if [ -n "GUID" ]; then
 	uefi -r $GUID | gunzip -c > $TMPFILE \
 	|| die "Failed to read config GUID from ROM"
 
-	if [ "$CONFIG_TPM" = "y" ]; then
-		tpm extend -ix "$CONFIG_PCR" -if $TMPFILE \
-		|| die "$filename: tpm extend failed"
-	fi
+	tpmx extend "$TMPFILE" "$CONFIG_PCR" \
+	|| die "$filename: tpm extend failed"
 
 	( cd / ; cpio -iud < $TMPFILE 2>/dev/null ) \
 	|| die "Failed to extract config GUID"
diff --git a/initrd/sbin/insmod b/initrd/sbin/insmod
--- a/initrd/sbin/insmod
+++ b/initrd/sbin/insmod
@@ -15,7 +15,6 @@ if [ -z "$MODULE_PCR" ]; then
 	MODULE_PCR=5
 fi
 
-
 if [ -z "$MODULE" ]; then
 	die "Usage: $0 module [args...]"
 fi
@@ -24,19 +23,12 @@ if [ ! -r "$MODULE" ]; then
 	die "$MODULE: not found?"
 fi
 
-if [ ! -r /sys/class/tpm/tpm0/pcrs -o ! -x /bin/tpm ]; then
-	tpm_missing=1
-fi
+tpmx extend "$MODULE" "$MODULE_PCR" || die "$MODULE: tpm extend failed"
 
-if [ -z "$tpm_missing" ]; then
-	tpm extend -ix "$MODULE_PCR" -if "$MODULE" \
-	|| die "$MODULE: tpm extend failed"
-fi
-
-if [ ! -z "$*" -a -z "$tpm_missing" ]; then
+if [ ! -z "$*" ]; then
 	TMPFILE=/tmp/insmod.$$
 	echo "$@" > $TMPFILE
-	tpm extend -ix "$MODULE_PCR" -if $TMPFILE \
+	tpmx extend $TMPFILE "$MODULE_PCR" \
 	|| die "$MODULE: tpm extend on arguments failed"
 fi
 
