initrd/bin/cbfs-init: add error check for flashrom command
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
Signed-off-by: Thomas Clarke <tonux@riseup.net>

diff --git a/initrd/bin/cbfs-init b/initrd/bin/cbfs-init
--- a/initrd/bin/cbfs-init
+++ b/initrd/bin/cbfs-init
@@ -18,8 +18,9 @@ fi
 
 if [ "$CONFIG_CBFS_VIA_FLASHROM" = "y" ]; then
 	# Use flashrom directly, because we don't have /tmp/config with params for flash.sh yet
-	/bin/flashrom -p internal --fmap -i COREBOOT -i FMAP -r /tmp/cbfs-init.rom > /dev/null 2>&1
-	CBFS_ARG=" -o /tmp/cbfs-init.rom"
+	/bin/flashrom -p internal --fmap -i COREBOOT -i FMAP -r /tmp/cbfs-init.rom > /dev/null 2>&1 \
+		&& CBFS_ARG=" -o /tmp/cbfs-init.rom" \
+		|| echo "Failed reading Heads configuration from flash! Some features may not be available."
 fi
 
 # Load individual files
