- OEM mode is enforced on HOTP/TOTP sealed clean hardware. - OEM is enforced by touching /boot/oem - OEM can be provisioned automatically if /media/oem-provisioning exists 	which feeds all the secrets automatically. - LUKS rencryption script added, which reencrypts and change Disk Recevory Key passphrase - LibremKey/Nitrokey factory reset script added, which takes user input first and then change key size, generate keys, exports them and flash rom. 	-Todo: Reset code should be added later on. (To unlock Admin. Else, a DoS is possible on a USB key)
- Contains uniformaization of langage.
- some shellcheck improved code
- LUKS Disk Unlock Key works properly
	-LVM volumes and disk devices are automatically detected
- GPG modules were retouched to remove invalid configure options which generated warnings
- LibremKey/Nitrokey is named everywhere for proper credit of partnership for HOTP
... And a lot of other smaller fixes...

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -6,12 +6,49 @@ CONFIG_BOOT_GUI_MENU_NAME='Heads Boot Menu'
 . /etc/functions
 . /tmp/config
 
-mount_boot()
-{
-  # Mount local disk if it is not already mounted
-  if ! grep -q /boot /proc/mounts ; then
-    mount -o ro /boot \
-      || recovery "Unable to mount /boot"
+file_selector() {
+  FILE=""
+  FILE_LIST=$1
+  MENU_MSG=${2:-"Choose the file"}
+  # create file menu options
+  if [ $(cat "$FILE_LIST" | wc -l) -gt 0 ]; then
+    option=""
+    while [ -z "$option" ]
+    do
+      MENU_OPTIONS=""
+      n=0
+      while read option
+      do
+        n=$(expr $n + 1)
+        option=$(echo "$option" | tr " " "_")
+        MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
+      done < $FILE_LIST
+
+      MENU_OPTIONS="$MENU_OPTIONS a Abort"
+      whiptail --clear --title "Select your File" \
+        --menu "${MENU_MSG} [1-$n, a to abort]:" 20 120 8 \
+        -- $MENU_OPTIONS \
+        2>/tmp/whiptail || die "Aborting"
+
+      option_index=$(cat /tmp/whiptail)
+
+      if [ "$option_index" = "a" ]; then
+        option="a"
+        return
+      fi
+
+      option=$(head -n "$option_index" "$FILE_LIST" | tail -1)
+      if [ "$option" == "a" ]; then
+        return
+      fi
+    done
+    if [ -n "$option" ]; then
+      FILE=$option
+    fi
+  else
+    whiptail $CONFIG_ERROR_BG_COLOR --title 'ERROR: No Files Found' \
+      --msgbox "No Files found matching the pattern. Aborting." 16 60
+    exit 1
   fi
 }
 verify_global_hashes()
@@ -62,11 +99,11 @@ verify_global_hashes()
 update_checksums()
 {
   if (whiptail --title 'Update Checksums and sign all files in /boot' \
-      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that the files in /boot have not been tampered with.\n\nYou will need your GPG key to continue and this change will modify your disk.\n\nDo you want to continue?" 16 90) then
+      --yesno "You have chosen to update the checksums and sign all of the files in /boot.\n\nThis means that you trust that the files in /boot have not been tampered\n with.\n\nYou will need your GPG key to continue and this change will modify your\n disk.\n\nDo you want to continue?" 16 90) then
     mount_boot
     mount -o rw,remount /boot
 
-    cd /boot
+    cd /boot || die "Not able to change directory to /boot."
     find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
     DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
     echo $DEFAULT_FILES | xargs sha256sum > /boot/kexec_default_hashes.txt
@@ -92,17 +129,243 @@ update_checksums()
 update_totp()
 {
   echo "Scan the QR code to add the new TOTP secret"
-  /bin/seal-totp
+  /bin/seal-totp $CONFIG_BOARD
   if [ -x /bin/libremkey_hotp_verification ]; then
-    echo "Once you have scanned the QR code, hit Enter to configure your Librem Key"
+    echo "Once you have scanned the QR code, hit Enter to configure your LibremKey/Nitrokey"
     read
     /bin/seal-libremkey
+    while [ $? -ne 0 ];do
+      echo -e "\n\nSealing HOTP secret into LibremKey/Nitrokey failed. Let's try again by resealing both TOTP and HOTP."
+      update_totp
+      /bin/seal-libremkey
+    done
   else
     echo "Once you have scanned the QR code, hit Enter to reboot"
     read
   fi
   /bin/reboot
 }
+read_oem_file()
+{
+  echo "Mounting USB drive to provision OEM reownership from /media/oem-provisioning..."
+  /bin/mount-usb || warn "Unable to mount USB device. Continuing"
+  if [ -e /media/oem-provisioning ]; then
+    oem_gpg_Admin_PIN=$(grep "oem_gpg_Admin_PIN" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_gpg_Admin_PIN" ]; then
+      export oem_gpg_Admin_PIN="$oem_gpg_Admin_PIN"
+    else
+      unset oem_gpg_Admin_PIN
+    fi
+  
+    oem_gpg_User_PIN=$(grep "oem_gpg_User_PIN" /media/oem-provisioning | cut -d "=" -f2) 
+    if [ -n "$oem_gpg_User_PIN" ]; then
+      export oem_gpg_User_PIN="$oem_gpg_User_PIN"
+    else
+      unset oem_gpg_User_PIN 
+    fi
+
+    oem_gpg_real_name=$(grep "oem_gpg_real_name" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_gpg_real_name" ]; then
+      export oem_gpg_real_name="$oem_gpg_real_name"
+    else
+      unset oem_gpg_real_name
+    fi
+
+    oem_gpg_email=$(grep "oem_gpg_email" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_gpg_email" ]; then
+      export oem_gpg_email="$oem_gpg_email"
+    else
+      unset oem_gpg_email 
+    fi
+
+    oem_gpg_comment=$(grep "oem_gpg_comment" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_gpg_comment" ]; then
+      export oem_gpg_comment="$oem_gpg_comment"
+    else
+      unset oem_gpg_comment
+    fi
+
+    oem_luks_actual_Disk_Recovery_Key=$(grep "oem_luks_actual_Disk_Recovery_Key" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_luks_actual_Disk_Recovery_Key" ]; then
+      export oem_luks_actual_Disk_Recovery_Key="$oem_luks_actual_Disk_Recovery_Key"
+    else
+      unset oem_luks_actual_Disk_Recovery_Key
+    fi
+
+    oem_luks_new_Disk_Recovery_Key=$(grep "oem_luks_new_Disk_Recovery_Key" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_luks_new_Disk_Recovery_Key" ]; then
+      export oem_luks_new_Disk_Recovery_Key="$oem_luks_new_Disk_Recovery_Key"
+    else
+      unset oem_luks_new_Disk_Recovery_Key
+    fi
+
+    oem_luks_Disk_Unlock_Key=$(grep "oem_luks_Disk_Unlock_Key" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_luks_Disk_Unlock_Key" ]; then
+      export oem_luks_Disk_Unlock_Key="$oem_luks_Disk_Unlock_Key"
+    else
+      unset oem_luks_Disk_Unlock_Key
+    fi
+
+    oem_TPM_Owner_Password=$(grep "oem_TPM_Owner_Password" /media/oem-provisioning | cut -d "=" -f2)
+    if [ -n "$oem_TPM_Owner_Password" ]; then
+      export oem_TPM_Owner_Password="$oem_TPM_Owner_Password"
+    else
+      unset oem_TPM_Owner_Password
+    fi
+  
+    export oem_configuration_read=1
+  fi
+}
+check_onboarding_progress()
+{
+  mount_boot
+  if [ -e /boot/oem ]; then
+    res=$(grep onboarding /boot/oem 2>&1 > /dev/null)
+    if [ $? -ne 0 ];then
+      #Show Onboarding menu once.
+      whiptail --title 'Hardware reownership Wizard' --msgbox \
+       "The received hardware is currently owned by $oem_name.\nWe will change that.\n\nThis Wizard will otherwise make you own your own hardware by:\n1-Reencrypting encrypted drive content (LUKS container)\n2-Changing LUKS Disk Recovery Key and it's passphrase\n3-Resetting your LibremKey/Nitrokey Pro v2 to factory defaults\n4-Setting User and Admin PINs into your LibremKey/NitroKey\n4-Generating keys in it, exporting public key and\n importing it in the rom prior to reprogramming the SPI flash with it\n6-Taking integrity measures of all /boot files and sign the resulting\n checksum file with yourLibremKey/Nitrokey Pro\n6-Owning your Trusted Platform Module (TPM)\n\nScan the QR Code with an OTP app only after Reset the TPM last phase.\n\nHit Enter to continue." 20 20
+      whiptail --title 'Hardware reownership Wizard' --msgbox \
+       "On the next screen, MAKE SURE THAT THE HOTP CODE IS: 'Success'\n\nIf it's not, reboot your hardware with your Librem/Nitrokey inserted.\n\nIf the HOTP code is still invalid, your hardware may been tampered with in\ntransit. Contact $oem_name." 20 20
+      totp_confirm="O"
+      echo $totp_confirm > /tmp/whiptail
+      mount -o remount,rw /boot
+      echo "onboarding" >> /boot/oem
+      mount -o remount,ro /boot
+    fi
+    res=$(grep luks_reencrypted /boot/oem 2>&1 > /dev/null)
+    if [ $? -ne 0 ];then
+      export reownership_state="luks_reencryption"
+      totp_confirm="R"
+      echo $totp_confirm > /tmp/whiptail
+      return
+    fi
+    res=$(grep luks_passwd_changed /boot/oem 2>&1 > /dev/null)
+    if [ $? -ne 0 ];then
+      export reownership_state="luks_password_change"
+      totp_confirm="R"
+      return
+    fi
+    res=$(grep gpg_factory_resetted /boot/oem 2>&1 > /dev/null)
+    if [ $? -ne 0 ];then
+      /bin/factory-reset-nitrokey-libremkey.sh
+      return
+    fi
+    res=$(grep tpm_reowned /boot/oem 2>&1 > /dev/null)
+    if [ $? -ne 0 ];then
+      totp_confirm="p"
+      echo $totp_confirm > /tmp/whiptail
+      return
+    fi
+    if [ $(grep -E "luks_reencrypted|luks_passwd_changed|gpg_factory_resetted|tpm_reowned" /boot/oem | uniq | wc -l) -eq 4 ];then
+      if [ $HOTP = "Success" ];then
+        mount -o remount,rw /boot
+        rm /boot/oem
+        mount -o remount,ro /boot
+        unset totp_confirm
+        unset reownership_state
+        whiptail --title 'DISK UNLOCK KEY ADVICE 1/3' --msgbox \
+          "***You SHOULD SET a new Disk Unlock Key for your own data privacy!!!***\n\nDoing so, a witness will only be able to type observed Disk Unlock\n Key passphrase from this computer and won't be able on a cloned\n copy of this disk.\n\nThe release of Disk Unlock Key happens ONLY if TPM attests firmware\nintegrity, and only if Disk Unlock Key passphrase is valid.\n\nPlease hit Enter to continue" 30 60
+
+        whiptail --title 'DISK UNLOCK KEY ADVICE 2/3' --msgbox \
+          "Otherwise, typing your Disk Recovery Key passphrase at boot puts you\nat risk. Someone could clone your disk and type that witnessed\npassphrase and access your data both locally and from a cloned\ndisk.\n\nCoupled with a strong passphrase, this improves your data privacy.\nCONSIDER YOURSELF WARNED.\n\nPlease hit Enter to continue" 30 60
+
+        whiptail --title 'DISK UNLOCK KEY ADVICE 3/3' --msgbox \
+          "To set Disk Unlock Key, released by the TPM only if firmware integrity\n is attested:\n\nSelect from Main menu:\n\nAdvanced Options menu -> Other Boot Options -> Show OS boot menu\n1-Then select the first boot option proposed (dynamic option)\n2-Then,answer Y when asked to add Disk Unlock Key to the TPM.\n\nYou will be prompted to set one in the following steps.\n\nPlease hit Enter to continue" 30 60
+        return 
+      else
+        #Deal with corner case where after inserting key in previous step, HOTP seal fails with provided good password.
+        #In that case, we regenerate HOTP and TOTP
+        totp_confirm="g"
+        echo $totp_confirm > /tmp/whiptail
+      fi
+    fi
+  else
+    reset_disk_unlock_key
+    return
+  fi  
+}
+reset_disk_unlock_key()
+{
+  mount_boot
+  
+  if [ "$CONFIG_TPM" = n ]; then
+    TOTP="NO TPM"
+  else
+    TOTP=`unseal-totp`
+    if [ $? -ne 0 ]; then
+      echo "Error generating TOTP code. We will regenerate it now."
+      update_totp
+      continue
+    elif [ -x /bin/libremkey_hotp_verification ]; then
+      HOTP=`unseal-hotp`
+      enable_usb
+      if ! libremkey_hotp_verification info ; then
+        whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert Your LibremKey/Nitrokey' --msgbox "Your LibremKey/Nitrokey was not detected.\n\nPlease insert your LibremKey/Nitrokey" 30 90
+      fi
+      # Don't output HOTP codes to screen, so as to make replay attacks harder
+      libremkey_hotp_verification check "$HOTP"
+      case "$?" in
+        0 )
+          HOTP="Success"
+        ;;
+        4 )
+          HOTP="Invalid code"
+          MAIN_MENU_BG_COLOR=$CONFIG_ERROR_BG_COLOR
+        ;;
+        * )
+          HOTP="Error checking code, Insert LibremKey/Nitrokey and retry"
+          MAIN_MENU_BG_COLOR=$CONFIG_WARNING_BG_COLOR
+        ;;
+      esac
+    else
+      HOTP='N/A'
+    fi
+      
+    if [ $HOTP = "Success" ];then
+      mount -o remount,rw /boot
+      rm /boot/reset_disk_unlock_key
+      mount -o remount,ro /boot
+      verify_global_hashes
+      kexec-select-boot -m -b /boot -c "grub.cfg" -g
+      continue
+    else
+      echo -e "HOTP status: $HOTP\n\nHit Enter to regenerate new TOTP/HOTP codes."
+      read
+      update_totp
+    fi
+    continue
+  fi
+}
+
+mount_boot
+if [ -e /boot/oem ];then
+  if [ -z "$oem_configuration_read" ]; then
+    #Read /media/oem-provisioning file once to read provisioned secrets
+    read_oem_file
+    
+    oem_name=$(grep "oem_name" /boot/oem | awk -F '=' {'print $2'})
+    if [ -n "$oem_name" ]; then
+      export oem_name="$oem_name"
+    else
+      oem_name="your OEM"
+      export oem_name="$oem_name"
+    fi
+  fi
+fi
+
+
+#TODO:validate that resetting disk unlock key only happens when /boot/oem doesn't exist anymore. Should happen after TPM reset.
+#Flashing modifies measurements, which should trigger TOTP/HOTP resealing. That happens when inserting gpg public key.
+#Measurements become invalid when TPM is reset, also.
+if [ -e /boot/reset_disk_unlock_key ] && [ ! -e /boot/oem ]; then
+  if (whiptail $CONFIG_WARNING_BG_COLOR --title "WARNING: You must change your Disk Unlock Key" \
+        --yesno "You just updated the ROM, which requires resealing TOTP/HOTP secrets.\nTPM released Disk Unlock Key stored in LUKS header must also be regenerated.\n\nIf you did not modify the ROM, this might be a sign of system compromise.\nIn that case, you should say No here and investigate." 30 90) then
+    reset_disk_unlock_key
+  else
+    recovery "User refused to update TOTP/HOTP following what seemed to be a ROM update. Time to investigate changes manually."
+  fi
+fi
 
 last_half=X
 while true; do
@@ -121,6 +384,7 @@ while true; do
 
       totp_confirm=$(cat /tmp/whiptail)
   fi
+  
   if [ "$totp_confirm" = "i" -o -z "$totp_confirm" ]; then
     # update the TOTP code every thirty seconds
     date=`date "+%Y-%m-%d %H:%M:%S"`
@@ -132,13 +396,14 @@ while true; do
       last_half=$half;
       TOTP=`unseal-totp`
       if [ $? -ne 0 ]; then
+        #Normal path. We give user a choice.
         whiptail $CONFIG_ERROR_BG_COLOR --clear --title "ERROR: TOTP Generation Failed!" \
           --menu "ERROR: Heads couldn't generate the TOTP code.\n\nIf this is the first time the system has booted, you should reset the TPM\nand set your own password\n\nIf you just reflashed your BIOS, you'll need to generate a new TOTP secret.\n\nIf you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n\nHow would you like to proceed?" 30 90 4 \
           'g' ' Generate new TOTP/HOTP secret' \
           'i' ' Ignore error and continue to default boot menu' \
           'p' ' Reset the TPM' \
           'x' ' Exit to recovery shell' \
-          2>/tmp/whiptail || recovery "GUI menu failed"
+        2>/tmp/whiptail || recovery "GUI menu failed"
 
         totp_confirm=$(cat /tmp/whiptail)
       fi
@@ -150,10 +415,10 @@ while true; do
       HOTP=`unseal-hotp`
       enable_usb
       if ! libremkey_hotp_verification info ; then
-        whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert Your Librem Key' --msgbox "Your Librem Key was not detected.\n\nPlease insert your Librem Key" 30 90
+        whiptail $CONFIG_WARNING_BG_COLOR --clear --title 'WARNING: Please Insert Your LibremKey/Nitrokey' --msgbox "Your LibremKey/Nitrokey was not detected.\n\nPlease insert your LibremKey/Nitrokey" 30 90
         fi
       # Don't output HOTP codes to screen, so as to make replay attacks harder
-      libremkey_hotp_verification check $HOTP
+      libremkey_hotp_verification check "$HOTP"
       case "$?" in
         0 )
           HOTP="Success"
@@ -163,7 +428,7 @@ while true; do
           MAIN_MENU_BG_COLOR=$CONFIG_ERROR_BG_COLOR
         ;;
         * )
-          HOTP="Error checking code, Insert Librem Key and retry"
+          HOTP="Error checking code, Insert LibremKey/Nitrokey and retry"
           MAIN_MENU_BG_COLOR=$CONFIG_WARNING_BG_COLOR
         ;;
       esac
@@ -171,14 +436,32 @@ while true; do
       HOTP='N/A'
     fi
 
-    whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME" \
-      --menu "$date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
-      'y' ' Default boot' \
-      'a' ' Advanced Settings -->' \
-      'x' ' Exit to recovery shell' \
-      2>/tmp/whiptail || recovery "GUI menu failed"
+    if [ -e /boot/oem ]; then
+      check_onboarding_progress
+  	  totp_confirm="O"
+      echo $totp_confirm > /tmp/whiptail
+    else
+      whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME" \
+        --menu "Greenwich Mean Time (GMT) : $date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
+        'y' ' Default boot' \
+        'a' ' Advanced Settings -->' \
+        'x' ' Exit to recovery shell' \
+        2>/tmp/whiptail || recovery "GUI menu failed"
+      totp_confirm=$(cat /tmp/whiptail)
+    fi
+  fi
 
-    totp_confirm=$(cat /tmp/whiptail)
+  if [ "$totp_confirm" = "O" ]; then
+    whiptail $MAIN_MENU_BG_COLOR --clear --title "$CONFIG_BOOT_GUI_MENU_NAME: Reownership" \
+        --menu "Greenwich Mean Time (GMT) : $date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
+        'C' ' Continue ownership of devices' \
+        'x' ' Exit to recovery shell' \
+        2>/tmp/whiptail || recovery "GUI menu failed"
+      totp_confirm=$(cat /tmp/whiptail)
+  fi
+
+  if [ "$totp_confirm" = "C" ]; then
+    check_onboarding_progress
   fi
 
   if [ "$totp_confirm" = "a" ]; then
@@ -186,10 +469,11 @@ while true; do
       --menu "Configure Advanced Settings" 20 90 10 \
       'o' ' Other Boot Options -->' \
       't' ' TPM/TOTP/HOTP Options -->' \
-      's' ' Update checksums and sign all files in /boot' \
-      'c' ' Change configuration settings -->' \
-      'f' ' Flash/Update the BIOS -->' \
       'G' ' GPG Options -->' \
+      'f' ' Flash/Update the BIOS -->' \
+      'c' ' Change configuration settings -->' \
+      's' ' Update checksums and sign all files in /boot' \
+      'R' ' Reencrypt LUKS container' \
       'r' ' <-- Return to main menu' \
       2>/tmp/whiptail || recovery "GUI menu failed"
 
@@ -260,8 +544,16 @@ while true; do
 
   if [ "$totp_confirm" = "p" ]; then
     if (whiptail --title 'Reset the TPM' \
-        --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
+        --yesno "This will clear the TPM content and reset TPM Owner password.\n\nDo you want to proceed?" 16 90) then
       /bin/tpm-reset
+      
+      #set flag in oem file
+      mount_boot
+      if [ -s /boot/oem ];then
+        mount -o remount,rw /boot
+        echo "tpm_reowned" >> /boot/oem
+        mount -o remount,ro /boot
+      fi
 
       # now that the TPM is reset, remove invalid TPM counter files
       mount_boot
@@ -327,6 +619,11 @@ while true; do
 
   if [ "$totp_confirm" = "G" ]; then
     gpg-gui.sh
+    continue
+  fi
+
+  if [ "$totp_confirm" = "R" ]; then
+    /bin/reencrypt-luks
     continue
   fi
 
diff --git a/initrd/bin/kexec-insert-key b/initrd/bin/kexec-insert-key
--- a/initrd/bin/kexec-insert-key
+++ b/initrd/bin/kexec-insert-key
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Unseal a disk key from TPM and add to a new initramfs
+# Unseal a Disk Unlock Key from TPM and add to a new initramfs
 set -e -o pipefail
 . /etc/functions
 
@@ -23,10 +23,10 @@ if [ -r "$TMP_KEY_LVM" ]; then
 		die "No LVM volume group defined for activation"
 	fi
 	lvm vgchange -a y $VOLUME_GROUP \
-		|| die "$VOLUME_GROUP: unable to activate volume group"
+		|| die "$VOLUME_GROUP: Unable to activate volume group"
 fi
 
-# Measure the LUKS headers before we unseal the disk key
+# Measure the LUKS headers before we unseal the Disk Unock Key
 cat "$TMP_KEY_DEVICES" | cut -d\  -f1 | xargs /bin/qubes-measure-luks \
 	|| die "LUKS measure failed"
 
@@ -37,12 +37,12 @@ INITRD_DIR=/tmp/secret/initrd
 SECRET_CPIO=/tmp/secret/initrd.cpio
 mkdir -p "$INITRD_DIR/etc"
 
-# Attempt to unseal the disk key from the TPM
+# Attempt to unseal the Disk Unlock Key from the TPM
 # should we give this some number of tries?
 unseal_failed="n"
 if ! kexec-unseal-key "$INITRD_DIR/secret.key" ; then
 	unseal_failed="y"
-	echo "!!! Failed to unseal the TPM LUKS disk key"
+	echo "!!! Failed to unseal the TPM LUKS Disk Unlock Key"
 fi
 
 # Override PCR 4 so that user can't read the key
@@ -54,14 +54,14 @@ if [ "$unseal_failed" = "y" ]; then
 	confirm_boot="n"
 	read \
 		-n 1 \
-		-p "Do you wish to boot and use the disk recovery key? [Y/n] " \
+		-p "Do you wish to boot and use the Disk Recovery Key? [Y/n] " \
 		confirm_boot
 
 	if [ "$confirm_boot" != 'y' \
 		-a "$confirm_boot" != 'Y' \
 		-a -n "$confirm_boot" ] \
 	; then
-		die "!!! Aborting boot due to failure to unseal TPM disk key"
+		die "!!! Aborting boot due to failure to unseal TPM Disk Unlock Key"
 	fi
 fi
 
diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -5,24 +5,24 @@ set -e -o pipefail
 . /etc/functions
 
 while getopts "b:d:p:i:" arg; do
-	case $arg in
-		b) bootdir="$OPTARG" ;;
-		d) paramsdev="$OPTARG" ;;
-		p) paramsdir="$OPTARG" ;;
-		i) index="$OPTARG" ;;
-	esac
+  case $arg in
+    b) bootdir="$OPTARG" ;;
+    d) paramsdev="$OPTARG" ;;
+    p) paramsdir="$OPTARG" ;;
+    i) index="$OPTARG" ;;
+  esac
 done
 
 if [ -z "$bootdir" -o -z "$index" ]; then
-	die "Usage: $0 -b /boot -i menu_option "
+  die "Usage: $0 -b /boot -i menu_option "
 fi
 
 if [ -z "$paramsdev" ]; then
-	paramsdev="$bootdir"
+  paramsdev="$bootdir"
 fi
 
 if [ -z "$paramsdir" ]; then
-	paramsdir="$bootdir"
+  paramsdir="$bootdir"
 fi
 
 bootdir="${bootdir%%/}"
@@ -33,106 +33,213 @@ TMP_MENU_FILE="/tmp/kexec/kexec_menu.txt"
 ENTRY_FILE="$paramsdir/kexec_default.$index.txt"
 HASH_FILE="$paramsdir/kexec_default_hashes.txt"
 
-if [ ! -r "$TMP_MENU_FILE" ]; then
-	die "No menu options available, please run kexec-select-boot"
+
+lvm_suggest=$(lvm vgscan|awk -F '"' {'print $1'}|tail -n +2)
+num_lvm=$(echo "$lvm_suggest"|wc -l)
+if [ "$num_lvm" -eq 1 ] && [ -n "$lvm_suggest" ]; then
+  lvm_volume_group=$lvm_suggest
+elif [ -z "$lvm_suggest" ]; then
+  num_lvm=0
 fi
 
-entry=`head -n $index $TMP_MENU_FILE | tail -1`
+devices_suggest=$(blkid | cut -d ':' -f 1 | while read device;do cryptsetup isLuks "$device";if [ $(echo $?) == 0 ]; then echo "$device";fi; done | sort)
+num_devices=$(echo "$devices_suggest"|wc -l)
+if [ "$num_devices" -eq 1 ]; then
+  key_devices=$devices_suggest
+else
+  devices_suggest=$(echo $devices_suggest)
+fi
+
+
+if [ ! -r "$TMP_MENU_FILE" ]; then
+  die "No menu options available, please run kexec-select-boot"
+fi
+
+entry=$(head -n "$index" $TMP_MENU_FILE | tail -1)
 if [ -z "$entry" ]; then
-	die "Invalid menu index $index"
+  die "Invalid menu index $index"
 fi
 
 KEY_DEVICES="$paramsdir/kexec_key_devices.txt"
 KEY_LVM="$paramsdir/kexec_key_lvm.txt"
 save_key="n"
+
 if [ "$CONFIG_TPM" = "y" ]; then
-	if [ ! -r "$KEY_DEVICES" ]; then
-		read \
-			-n 1 \
-			-p "Do you wish to add a disk encryption to the TPM [y/N]: " \
-			add_key_confirm
-		echo
+  if [ ! -s "$KEY_DEVICES" ]; then
+    read \
+      -n 1 \
+      -p "Do you wish to add a Disk Unlock Key to the TPM [Y/n]: " \
+      add_key_confirm
+    echo
 
-		if [ "$add_key_confirm" = "y" \
-			-o "$add_key_confirm" = "Y" ]; then
-			lvm_suggest="e.g. qubes_dom0 or blank"
-			devices_suggest="e.g. /dev/sda2 or blank"
-			save_key="y"
-		fi
-	else
-		read \
-			-n 1 \
-			-p "Do you want to reseal a disk key to the TPM [y/N]: " \
-			change_key_confirm
-		echo
+    if [ "$add_key_confirm" = "y" ] || [ "$add_key_confirm" = "Y" ] || [ -z "$add_key_confirm" ]; then
+      if [ "$num_lvm" -gt 1 ]; then
+        //untested
+        selected_lvmdev_not_existing=1
+        while [ $selected_lvmdev_not_existing -ne 0 ];do
+        {
+            read \
+              -p "Encrypted LVM group? choose between: $lvm_suggest: " \
+              lvm_volume_group
 
-		if [ "$change_key_confirm" = "y" \
-			-o "$change_key_confirm" = "Y" ]; then
-			old_lvm_volume_group=""
-			if [ -r "$KEY_LVM" ]; then
-				old_lvm_volume_group=`cat $KEY_LVM` || true
-				old_key_devices=`cat $KEY_DEVICES \
-				| cut -d\  -f1 \
-				| grep -v "$old_lvm_volume_group" \
-				| xargs` || true
-			else
-				old_key_devices=`cat $KEY_DEVICES \
-				| cut -d\  -f1 | xargs` || true
-			fi
+            result=$(echo "$lvm_suggest" | grep -q "$lvm_volume_group") || selected_lvmdev_not_existing=1
+            if [ $? == 0 ]; then
+              selected_lvmdev_not_existing=0
+            fi
+        };done  
+      elif [ "$num_lvm" -eq 1 ]; then
+        echo "Single Encrypted LVM group found at $lvm_suggest. Using it."
+        lvm_volume_group=$lvm_suggest
+      else
+        echo "No encrypted LVM Group found."
+      fi
 
-			lvm_suggest="was '$old_lvm_volume_group'"
-			devices_suggest="was '$old_key_devices'"
-			save_key="y"
-		fi
-	fi
+      if [ "$num_devices" -gt 1 ]; then
+        selected_luksdev_not_existing=1
+        while [ $selected_luksdev_not_existing -ne 0 ];do
+        {
+          read \
+          -p "Encrypted devices? (choose between: $devices_suggest): " \
+          key_devices
 
-	if [ "$save_key" = "y" ]; then
-		echo "+++ LVM volume groups (lvm vgscan): "
-		lvm vgscan || true
+          result=$(echo "$devices_suggest" | grep -q "$key_devices") || selected_luksdev_not_existing=1
+          if [ $? == 0 ]; then
+            selected_luksdev_not_existing=0
+          fi
+        };done
+      elif [ "$num_devices" -eq 1 ]; then
+        echo "Single Encrypted Disk found at $devices_suggest. Using it."
+        key_devices=$devices_suggest
+      else
+        echo "No encrypted devices found."
+      fi
 
-		read \
-			-p "Encrypted LVM group? ($lvm_suggest): " \
-			lvm_volume_group
+    save_key="y"
+    else
+      die "User chose to not add Disk Unlock Key to the TPM"
+    fi
+  else
+    read \
+      -n 1 \
+      -p "Do you want to reseal a Disk Unlock Key to the TPM [Y/n]: " \
+      change_key_confirm
+    echo
 
-		echo "+++ Block devices (blkid): "
-		blkid || true
+    if [ "$change_key_confirm" = "y" ] || [ "$change_key_confirm" = "Y" ] || [ -z "$change_key_confirm" ]; then
+      old_lvm_volume_group=""
+      if [ -r "$KEY_LVM" ]; then
+        old_lvm_volume_group=$(cat "$KEY_LVM") || true
+        old_key_devices=$(cat "$KEY_DEVICES" \
+        | cut -d\  -f1 \
+        | grep -v "$old_lvm_volume_group" \
+        | xargs) || true
+      else
+        old_key_devices=$(cat "$KEY_DEVICES" \
+        | cut -d\  -f1 | xargs) || true
+      fi
 
-		read \
-			-p "Encrypted devices? ($devices_suggest): " \
-			key_devices
+      lvm_suggest="$old_lvm_volume_group"
+      devices_suggest="$old_key_devices"
+      save_key="y"
+    else
+      echo -e "\n\nTo set a new Disk Unlock Key passphrase, different then Disk Recovery Key passphrase, resealing the Disk Unlock key to the TPM is needed.\n\nThe actual default boot option have been invalidated by a firmware upgrade or a firmware tampering.\nIf you are the origin of the change, you have already resealed TOTP/HOTP, prompted from TPM measurements mismatches.\n\nIt is strongly advised to set a new default boot option, which will add the Disk Unlock Key to the TPM.\n\nThe Disk Unlock Key passphrase you will choose at this step will be required of you at each machine startup and will protect the Disk Recovery Key passphrase from interested eyes.\n\nBy selecting a Disk Unlock Key passphrase, a camera that would see you type your Disk Unlock Key passphrase will only be able to access the content of your hard drive on this computer.\n\nMore critically, someone knowing your Disk Recovery Key passphrase would just have to clone your disk (which takes 30 minutes) and be able to access its content from any other computer later on.\nConsider yourself warned.\n"
+      die "User refused to reseal the Disk Unlock Key to the TPM"
+    fi
+  fi
 
-		save_key_params="-s -p $paramsdev"
-		if [ -n "$lvm_volume_group" ]; then
-			save_key_params="$save_key_params -l $lvm_volume_group $key_devices"
-		else
-			save_key_params="$save_key_params $key_devices"
-		fi
-		echo "Running kexec-save-key with params: $save_key_params"
-		kexec-save-key $save_key_params \
-			|| die "Failed to save the disk key"
-	fi
+  if [ "$save_key" = "y" ]; then
+    if [ -n "$old_key_devices" ] || [ -n "$old_lvm_volume_group" ]; then
+      read \
+        -n 1 \
+        -p "Do you want to reuse configured Encrypted LVM groups/Block devices? (Y/n):" \
+        reuse_past_devices
+       echo
+      if [ "$reuse_past_devices" = "y" ] || [ "$reuse_past_devices" = "Y" ] || [ -z "$reuse_past_devices" ]; then
+        if [ -z "$key_devices" ] && [ -n "$old_key_devices" ]; then
+          key_devices="$old_key_devices"
+        fi
+        if [ -z "$lvm_volume_group" ] && [ -n "$old_lvm_volume_group" ]; then
+          lvm_volume_group="$old_lvm_volume_group"
+        fi
+      else
+        if [ "$num_lvm" -eq 1 ]; then
+          echo "Single Encrypted LVM group found at $lvm_suggest. Using it."
+          lvm_volume_group="$lvm_suggest"
+        elif [ "$num_lvm" -gt 1 ]; then
+          //untested
+          selected_lvmdev_not_existing=1
+          while [ $selected_lvmdev_not_existing -ne 0 ];do
+          {
+              read \
+                -p "Encrypted LVM group? (choose between: $lvm_suggest): " \
+                lvm_volume_group
+
+              result=$(echo "$lvm_suggest" | grep -q "$lvm_volume_group") || selected_lvmdev_not_existing=1
+              if [ $? == 0 ]; then
+                selected_lvmdev_not_existing=0
+              fi
+          };done
+        else
+          echo "No encrypted LVM Group found."
+        fi
+
+        if [ "$num_devices" -eq 1 ]; then
+          echo "Single Encrypted Disk found at $devices_suggest. Using it."
+          key_devices="$devices_suggest"
+        elif [ "$num_devices" -gt 1 ]; then
+          selected_luksdev_not_existing=1
+            while [ $selected_luksdev_not_existing -ne 0 ];do
+            {
+              read \
+              -p "Encrypted devices? (choose between: $devices_suggest): " \
+              key_devices
+
+              result=$(echo "$devices_suggest" | grep -q "$key_devices") || selected_luksdev_not_existing=1
+              if [ $? == 0 ]; then
+                selected_luksdev_not_existing=0
+              fi
+            };done
+        else
+          echo "No encrypted devices found."
+        fi
+      fi
+    fi
+
+    save_key_params="-s -p $paramsdev"
+    if [ -n "$lvm_volume_group" ]; then
+      save_key_params="$save_key_params -l $lvm_volume_group $key_devices"
+    elif [ -n "$key_devices" ]; then
+      save_key_params="$save_key_params $key_devices"
+    else
+      die "No LVM Group nor encrypted devices provided."
+    fi
+  fi  
+  
+  echo -e "\nRunning kexec-save-key with params: $save_key_params\n"
+  kexec-save-key $save_key_params \
+  || die "Failed to save the Disk Unlock Key"
 fi
 
 # try to switch to rw mode
 mount -o rw,remount $paramsdev
 
 if [ ! -d $paramsdir ]; then
-	mkdir -p $paramsdir \
-	|| die "Failed to create params directory"
+  mkdir -p $paramsdir \
+  || die "Failed to create params directory"
 fi
 rm "$paramsdir/kexec_default.*.txt" 2>/dev/null || true
 echo "$entry" > $ENTRY_FILE
 cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f | \
-	xargs sha256sum > $HASH_FILE \
+  xargs sha256sum > $HASH_FILE \
 || die "Failed to create hashes of boot files"
 if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
-	die "Failed to write default config"
+  die "Failed to write default config"
 fi
 
 # sign and auto-roll config counter
 extparam=
 if [ "$CONFIG_TPM" = "y" ]; then
-	extparam=-u
+  extparam=-u
 fi
 kexec-sign-config -p $paramsdir $extparam \
 || die "Failed to sign default config"
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -3,7 +3,18 @@
 
 die() {
 	echo >&2 "$*";
+	read -p 'Hit enter to continue.'
 	exit 1;
+}
+
+debug(){
+  echo >&2 "$*";
+  read -p 'Hit enter to continue.'
+}
+
+error() {
+	echo >&2 "$*";
+  exit 1;
 }
 
 warn() {
@@ -41,7 +52,7 @@ pause_recovery() {
 }
 
 pcrs() {
-	head -8 /sys/class/tpm/tpm0/pcrs
+	head -9 /sys/class/tpm/tpm0/pcrs
 }
 
 confirm_totp()
@@ -118,6 +129,61 @@ enable_usb()
 	fi
 }
 
+file_selector() {
+  FILE=""
+  FILE_LIST=$1
+  MENU_MSG=${2:-"Choose the file"}
+  # create file menu options
+  if [ $(cat "$FILE_LIST" | wc -l) -gt 0 ]; then
+    option=""
+    while [ -z "$option" ]
+    do
+      MENU_OPTIONS=""
+      n=0
+      while read option
+      do
+        n=$(expr $n + 1)
+        option=$(echo "$option" | tr " " "_")
+        MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
+      done < $FILE_LIST
+
+      MENU_OPTIONS="$MENU_OPTIONS a Abort"
+      whiptail --clear --title "Select your File" \
+        --menu "${MENU_MSG} [1-$n, a to abort]:" 20 120 8 \
+        -- $MENU_OPTIONS \
+        2>/tmp/whiptail || die "Aborting"
+
+      option_index=$(cat /tmp/whiptail)
+
+      if [ "$option_index" = "a" ]; then
+        option="a"
+        return
+      fi
+
+      option=$(head -n "$option_index" "$FILE_LIST" | tail -1)
+      if [ "$option" == "a" ]; then
+        return
+      fi
+    done
+    if [ -n "$option" ]; then
+      FILE=$option
+    fi
+  else
+    whiptail $CONFIG_ERROR_BG_COLOR --title 'ERROR: No Files Found' \
+      --msgbox "No Files found matching the pattern. Aborting." 16 60
+    exit 1
+  fi
+}
+
+mount_boot()
+{
+  # Mount local disk if it is not already mounted
+  if ! grep -q /boot /proc/mounts ; then
+    mount -o ro /boot \
+      || recovery "Unable to mount /boot from $CONFIG_BOOT_DEV"
+  fi
+}
+
 confirm_gpg_card()
 {
 	read \
@@ -140,7 +206,6 @@ confirm_gpg_card()
 	|| die "gpg card read failed"
 }
 
-
 check_tpm_counter()
 {
   LABEL=${2:-3135106223}
@@ -148,10 +213,15 @@ check_tpm_counter()
 	# from it.
 	if [ -r "$1" ]; then
 		TPM_COUNTER=`grep counter- "$1" | cut -d- -f2`
-	else
-		warn "$1 does not exist; creating new TPM counter"
-		read -s -p "TPM Owner password: " tpm_password
-		echo
+  else 
+    warn "$1 does not exist; creating new TPM counter"
+    if [ -z "$oem_TPM_Owner_Password" ]; then
+		  read -s -p "TPM Owner password: " tpm_password
+		  echo
+    else
+      tpm_password=$(echo -n "$oem_TPM_Owner_Password")
+    fi
+
 		tpm counter_create \
 			-pwdo "$tpm_password" \
 			-pwdc '' \
@@ -198,7 +268,8 @@ check_config() {
 
 	if [ "$2" != "force" ]; then
 		if ! sha256sum `find $1/kexec*.txt` | gpgv $1/kexec.sig - ; then
-			die 'Invalid signature on kexec boot params'
+			die 'Invalid signature on kexec boot params. Investigate/Update checksums and sign all files in /boot.'
+      #TODO: Show which files failed integrity check!
 		fi
 	fi
 
