Moving reencrypt code into gui-init file selection code duplicated into gui-init

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -6,6 +6,52 @@ CONFIG_BOOT_GUI_MENU_NAME='Heads Boot Menu'
 . /etc/functions
 . /etc/config
 
+file_selector() {
+  FILE=""
+  FILE_LIST=$1
+  MENU_MSG=${2:-"Choose the file"}
+# create file menu options
+  if [ `cat "$FILE_LIST" | wc -l` -gt 0 ]; then
+    option=""
+    while [ -z "$option" ]
+    do
+      MENU_OPTIONS=""
+      n=0
+      while read option
+      do
+        n=`expr $n + 1`
+        option=$(echo $option | tr " " "_")
+        MENU_OPTIONS="$MENU_OPTIONS $n ${option}"
+      done < $FILE_LIST
+
+      MENU_OPTIONS="$MENU_OPTIONS a Abort"
+      whiptail --clear --title "Select your File" \
+        --menu "${MENU_MSG} [1-$n, a to abort]:" 20 120 8 \
+        -- $MENU_OPTIONS \
+        2>/tmp/whiptail || die "Aborting"
+
+      option_index=$(cat /tmp/whiptail)
+
+      if [ "$option_index" = "a" ]; then
+        option="a"
+        return
+      fi
+
+      option=`head -n $option_index $FILE_LIST | tail -1`
+      if [ "$option" == "a" ]; then
+        return
+      fi
+    done
+    if [ -n "$option" ]; then
+      FILE=$option
+    fi
+  else
+    whiptail $CONFIG_ERROR_BG_COLOR --title 'ERROR: No Files Found' \
+      --msgbox "No Files found matching the pattern. Aborting." 16 60
+    exit 1
+  fi
+}
+
 mount_boot()
 {
   # Mount local disk if it is not already mounted
@@ -190,6 +236,8 @@ while true; do
       's' ' Update checksums and sign all files in /boot' \
       'f' ' Flash/Update the BIOS -->' \
       'p' ' Reset the TPM' \
+      'F' ' Factory reset LibremKey/Nitrokey Pro v2' \
+      'R' ' Reencrypt LUKS container' \
       'n' ' TOTP/HOTP does not match after refresh, troubleshoot' \
       'r' ' <-- Return to main menu' \
       2>/tmp/whiptail || recovery "GUI menu failed"
@@ -307,6 +355,57 @@ while true; do
     flash-gui.sh
     continue
   fi
+  
+  if [ "$totp_confirm" = "F" ]; then
+    mount_boot
+    gpg_card_factory_reset
+    continue
+  fi
+  
+  if [ "$totp_confirm" = "R" ]; then
+    if (whiptail --title 'Reencrypt LUKS container with a new user selected strong passphrase?' \
+          --yesno "This will replace the actual Disk recovery key OR initially created when the system \nwas installed.\n\n The passphrase associated with this key will be asked to\nthe user in the following conditions:\n1-Every boot if no Disk encryption key was added to the TPM (through\n setting a default boot option and accepting to add Disk encryption key\n to the TPM)\n2-If the TPM fails (Hardware failure)\n3-If the firmware has been tampered with/upgraded/modified by the user\n\nThis process requires you to type the actual Disk recovery key passphrase\nand will delete Disk unlock key released by the TPM into LUKS (slot 1).\n\nIn the next prompt, you'll be asked to select which file corresponds to\nthe LUKS device container. Normally, it should be /dev/sda2.\n\nDo you want to proceed? Else you'll return to the main menu." 30 90) then
+      blkid | cut -d ':' -f 1 | while read device; do cryptsetup luksDump $device 2>&1; done| grep "LUKS header information"| awk -F " " '{print $NF}'|sort > /tmp/luks_devices.txt
+      file_selector "/tmp/luks_devices.txt"
+      if [ "$FILE" == "" ]; then
+        return
+      else
+        LUKS=$FILE
+        mount_boot
+        mount -o remount,rw /boot
+        echo "$LUKS $(cryptsetup luksUUID $LUKS)" > /boot/kexec_key_devices.txt
+        mount -o remount,ro /boot
+      fi
+      
+      whiptail --title 'Reencrypting LUKS container!' --msgbox \
+        "Please enter current Recovery key passphrase (slot 0)\nto reencrypt LUKS container.\n\nThen press Enter to continue." 30 60
+      cryptsetup-reencrypt -B 32 --use-directio $LUKS --key-slot 0
+        if [ $(echo $?) != 0 ]; then
+          whiptail --title 'Invalid LUKS passphrase?' --msgbox \
+            "The LUKS Recovery password was provided to you by the OEM over secure channel.\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\nTo do so, put OS ISO file with it's signature file on USB drive,\n And select Boot from USB\n\nPlease press Enter to continue." 30 60
+          continue
+        fi
+          
+      whiptail --title 'Changing LUKS Recovery key passphrase' --msgbox \
+        "Please enter current Recovery key passphrase (slot 0).\nThen choose a strong passphrase of your own.\n\n**DICEWARE passphrase methodology is STRONGLY ADVISED.**\n\nPlease hit Enter to continue" 30 60
+      cryptsetup luksChangeKey $LUKS --tries 3
+        if [ $(echo $?) != 0 ]; then
+          whiptail --title 'Invalid LUKS passphrase?' --msgbox \
+            "The LUKS Recovery password was provided to you by the OEM over secure channel.\nIf you previously changed it and do not remember it,\n you will have to reinstall Linux OS from a USB drive.\nTo do so, put OS ISO file with it's signature file on USB drive,\n And select Boot from USB\n\nPlease press Enter to continue." 30 60
+          continue
+        fi
+      whiptail --title 'DISK UNLOCK KEY ADVICE 1/3' --msgbox \
+        "You SHOULD SET a Disk unlock key for your own data privacy!!!***\nDoing so, a witness will only be able to type observed Disk unlock\npassphrase from this computer, not on a cloned copy of the disk.\n The TPM release of Disk unlock key happens ONLY if it attests firmware\nintegrity, an only if Disk unlock user passphrase is valid.\n\nPlease hit Enter to continue" 30 60
+      
+      whiptail --title 'DISK UNLOCK KEY ADVICE 2/3' --msgbox \
+        "Otherwise, typing Disk recovery key passphrase at boot puts you\nat risk. Someone could clone your disk and type that witnessed\npassphrase and access your data both locally and from cloned\ndisk. This is why strong passphrases are so important to data privacy.\nCONSIDER YOURSELF WARNED.\n\nPlease hit Enter to continue" 30 60
+      
+      whiptail --title 'DISK UNLOCK KEY ADVICE 3/3' --msgbox \
+        "To set a Disk Unlock Key, released by the TPM after it attests\nfirwmare integrity when combined with valid passphrase, select\nfrom Main menu:\n\nAdvanced Options menu -> Other Boot Options -> Show OS boot menu\n1-Then select the first boot option proposed (dynamic option)\n2-Then, answer Y when asked to add disk encryption to the TPM.\n\nPlease hit Enter to continue" 30 60
+      continue
+    fi
+  fi
+
 
   if [ "$totp_confirm" = "y" -o -n "$totp_confirm" ]; then
     # Try to boot the default
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -217,3 +217,158 @@ preserve_rom() {
 		fi
 	done
 }
+
+gpg_card_factory_reset()
+{
+  confirm_gpg_card
+  {
+    echo admin
+    echo factory-reset
+    echo y
+    echo yes
+  } | gpg --command-fd=0 --status-fd=1 --pinentry-mode=loopback --card-edit
+  
+  #Setting new passwords
+  gpgcard_user_pass1=1
+  gpgcard_user_pass2=2
+  gpgcard_admin_pass1=3
+  gpgcard_admin_pass2=4
+
+  while [[ "$gpgcard_user_pass1" != "$gpgcard_user_pass2" ]] || [[ ${#gpgcard_user_pass1} -lt 6 || ${#gpgcard_user_pass1} -gt 20 ]];do
+  {
+    echo "Choose a GPG card password that will be typed when using GPG smartcard. It needs to be a least 6 but not more then 20 characters:"
+    read -s gpgcard_user_pass1
+    echo "Retype user passphrase:"
+    read -s gpgcard_user_pass2
+    if [[ "$gpgcard_user_pass1" != "$gpgcard_user_pass2" ]]; then echo "Passwords typed were different."; fi
+  };done
+  gpgcard_user_pass=$gpgcard_user_pass1
+
+  while [[ "$gpgcard_admin_pass1" != "$gpgcard_admin_pass2" ]] || [[ ${#gpgcard_admin_pass1} -lt 8 || ${#gpgcard_admin_pass1} -gt 20 ]]; do
+  {
+    echo "Choose a GPG card password that will be typed when managing GPG smartcard. It needs to be a least 8 but not more then 20 characters:"
+    read -s gpgcard_admin_pass1
+    echo "Retype admin password:"
+    read -s gpgcard_admin_pass2
+    if [[ "$gpgcard_admin_pass1" != "$gpgcard_admin_pass2" ]]; then echo "Passwords typed were different."; fi
+  };done
+  gpgcard_admin_pass=$gpgcard_admin_pass1
+  
+  {
+    echo admin
+    echo passwd
+    echo 1
+    echo 123456 #Default user password after factory reset of card
+    echo "$gpgcard_user_pass"
+    echo "$gpgcard_user_pass"
+    echo 3
+    echo 12345678 #Default administrator password after factory reset of card
+    echo "$gpgcard_admin_pass"
+    echo "$gpgcard_admin_pass"
+    echo Q
+  } | gpg --command-fd=0 --status-fd=2 --pinentry-mode=loopback --card-edit
+  
+  #Set GPG card key attributes key sizes to 4096bits
+  {
+    echo admin
+    echo key-attr
+    echo 1 # RSA
+    echo 4096 #Signing key size set to maximum supported by SmartCard
+    echo "$gpgcard_admin_pass"
+    echo 1 # RSA
+    echo 4096 #Encryption key size set to maximum supported by SmartCard
+    echo "$gpgcard_admin_pass"
+    echo 1 # RSA
+    echo 4096 #Authentication key size set to maximum supported by SmartCard
+    echo "$gpgcard_admin_pass"
+  } | gpg --command-fd=0 --status-fd=2 --pinentry-mode=loopback --card-edit
+  
+  #Generate Encryption, Signing and Authentication keys
+  echo -e "\n\n"
+  echo -e "We will generate a GnuPG (GPG) keypair identifiable with the following text form:"
+  echo -e "Real Name (Comment) email@address.org" "\n" "\n"
+  echo -e "Enter your Real Name:"
+  read gpgcard_real_name
+  echo "Enter your email@adress.org:"
+  read gpgcard_email_address
+  echo "Enter Comment:"
+  read gpgcard_comment
+
+  echo "BE PATIENT! Generating 4096 bits Encryption, Signing and Authentication keys take around 5 minutes each! BE PATIENT!"
+
+  {
+    echo admin
+    echo generate
+    echo n
+    echo "$gpgcard_admin_pass"
+    echo "$gpgcard_user_pass"
+    echo 1y
+    echo "$gpgcard_real_name"
+    echo "$gpgcard_email_address"
+    echo "$gpgcard_comment"
+  } | gpg --command-fd=0 --status-fd=2 --pinentry-mode=loopback --card-edit --home=/.gnupg/
+  
+  #Export and inject public key and trustdb export into extracted rom with current user keys being wiped
+  rom=/tmp/coreboot.rom
+  
+  #remove invalid kexec_* signed files
+  mount -o remount,rw /boot && rm /boot/kexec* && mount -o remount,ro /boot
+
+  confirm_gpg_card
+  mount-usb
+  
+  #Copy generated public key, private_subkey, trustdb and artifacts to external media for backup: 
+  mount -o remount,rw /media 
+  mkdir -p /media/gpg_keys 
+  gpg --export --armor $gpgcard_email_address  > /media/gpg_keys/public.key
+  gpg --export-ownertrust > /media/gpg_keys/otrust.txt
+  cp -r ./.gnupg/* /media/gpg_keys/ 2> /dev/null
+
+  #Read rom
+  flash.sh -r $rom
+
+  #delete private/public gpg keys and otrust
+  cbfs -o $rom --list|grep -e pubring -e trustdb -e otrust|while read file; do cbfs -o $rom -d $file;done
+
+  #Insert public key and trustdb exports into reproducible rom:
+  cbfs -o $rom -a "heads/initrd/.gnupg/keys/public.key" -f /media/gpg_keys/public.key
+  cbfs -o $rom -a "heads/initrd/.gnupg/keys/otrust.txt" -f /media/gpg_keys/otrust.txt
+
+  #Flush changes to external media: 
+  mount -o remount,ro /media
+
+  #flash back rom with public key and trustdb into SPI flash
+  flash.sh -c $rom
+  
+  echo "Hit enter to reboot"
+  read
+  /bin/reboot
+}
+
+cryptsetup_reencrypt()
+{
+  if [ -s /boot/kexec_key_devices.txt ]; then
+    luks_container=$(cut -d ' ' -f1 /boot/kexec_key_devices.txt)
+
+    cryptsetup luksDump $luks_container|grep "Key Slot 1: ENABLED"
+    if [[ $? -eq 0 ]]; then
+      echo "We first need to delete the secondary LUKS decryption passphrase enforced when a default boot option was set."
+      echo "To reenforce it, select a new default boot option and answer yes to seal it with TPM measurements. This is advised." 
+      echo "You'll be asked to type the current Recovery LUKS encryption passphrase (slot 0) to delete the secondary passphrase. (slot 1)" 
+      echo "A new LUKS Recovery encryption passphrase of your choice will be asked in the next step."
+      echo -e "\n"
+      cryptsetup luksKillSlot $luks_container 1
+    fi
+
+    echo "We will now reencrypt the LUKS container with your own chosen LUKS recovery decryption passphrase."
+    echo "You will be asked to enter the actual recovery LUKS passphrase before choosing your own."
+    echo "CHOOSE IT CAREFULLY AND DO NOT FORGET IT. Good example: white elephant of Antartica"
+    echo "Reencrypting a fresh installation of QubesOS on a 240GB SSD drive can take up to 30 minutes. Be patient."
+    echo -e "\n"
+    cryptsetup-reencrypt -B 32 --use-directio $luks_container
+  else
+    echo "You have to reown the TPM, sign configurations with your GPG smartcard first and select a new default boot option!"
+    echo "Press enter to continue."
+    read
+  fi
+}
