gui-init: refactor into functions
Break menus and menu items into functions where possible.
Improves readability of code / functional flow, and
makes future refactoring easier.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -124,6 +124,67 @@ generate_totp_htop()
   fi
 }
 
+update_totp()
+{
+  # update the TOTP code every thirty seconds
+  date=`date "+%Y-%m-%d %H:%M:%S"`
+  seconds=`date "+%s"`
+  half=`expr \( $seconds % 60 \) / 30`
+  if [ "$CONFIG_TPM" = n ]; then
+    TOTP="NO TPM"
+  elif [ "$half" != "$last_half" ]; then
+    last_half=$half;
+    TOTP=`unseal-totp`
+    if [ $? -ne 0 ]; then
+      whiptail $BG_COLOR_ERROR --clear --title "ERROR: TOTP Generation Failed!" \
+        --menu "    ERROR: Heads couldn't generate the TOTP code.\n
+  If you have just completed a Factory Reset, or just reflashed
+  your BIOS, you should generate a new HOTP/TOTP secret.\n
+  If this is the first time the system has booted, you should
+  reset the TPM and set your own password.\n
+  If you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n
+  How would you like to proceed?" 30 90 4 \
+        'g' ' Generate new HOTP/TOTP secret' \
+        'i' ' Ignore error and continue to main menu' \
+        'p' ' Reset the TPM' \
+        'x' ' Exit to recovery shell' \
+        2>/tmp/whiptail || recovery "GUI menu failed"
+
+      totp_confirm=$(cat /tmp/whiptail)
+    fi
+  fi
+}
+
+update_hotp()
+{
+  if [ -x /bin/hotp_verification ]; then
+    HOTP=`unseal-hotp`
+    enable_usb
+    if ! hotp_verification info ; then
+      whiptail $BG_COLOR_WARNING --clear \
+--title "WARNING: Please Insert Your $HOTPKEY_BRANDING" \
+--msgbox "Your $HOTPKEY_BRANDING was not detected.\n\nPlease insert your $HOTPKEY_BRANDING" 30 90
+      fi
+    # Don't output HOTP codes to screen, so as to make replay attacks harder
+    hotp_verification check $HOTP
+    case "$?" in
+      0 )
+        HOTP="Success"
+      ;;
+      4 )
+        HOTP="Invalid code"
+        MAIN_MENU_BG_COLOR=$BG_COLOR_ERROR
+      ;;
+      * )
+        HOTP="Error checking code, Insert $HOTPKEY_BRANDING and retry"
+        MAIN_MENU_BG_COLOR=$BG_COLOR_WARNING
+      ;;
+    esac
+  else
+    HOTP='N/A'
+  fi
+}
+
 clean_boot_check()
 {
   # assume /boot mounted
@@ -153,6 +214,188 @@ clean_boot_check()
     "Clean Boot Detected - Perform OEM Factory Reset?" "$BG_COLOR_WARNING"
 }
 
+check_gpg_key()
+{
+  GPG_KEY_COUNT=`gpg -k 2>/dev/null | wc -l`
+  if [ $GPG_KEY_COUNT -eq 0 ]; then
+    whiptail $BG_COLOR_ERROR --clear --title "ERROR: GPG keyring empty!" \
+      --menu "ERROR: Heads couldn't find any GPG keys in your keyring.\n\nIf this is the first time the system has booted,\nyou should add a public GPG key to the BIOS now.\n\nIf you just reflashed a new BIOS, you'll need to add at least one\npublic key to the keyring.\n\nIf you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n\nHow would you like to proceed?" 30 90 4 \
+      'G' ' Add a GPG key to the running BIOS' \
+      'i' ' Ignore error and continue to main menu' \
+      'x' ' Exit to recovery shell' \
+      2>/tmp/whiptail || recovery "GUI menu failed"
+
+      totp_confirm=$(cat /tmp/whiptail)
+  fi
+}
+
+prompt_auto_default_boot()
+{
+  # save IFS before changing, restore after read
+  IFS_DEF=$IFS
+  IFS=''
+  first_pass=false
+  echo -e "\nHOTP verification success\n\n"
+  read -t $CONFIG_AUTO_BOOT_TIMEOUT -s -n 1 -p "Automatic boot in $CONFIG_AUTO_BOOT_TIMEOUT seconds unless interrupted by keypress... "
+  if [[ $? -ne 0 ]]; then
+    IFS=$IFS_DEF
+    # skip to default boot
+    totp_confirm='y'
+    echo -e "\n\nAttempting default boot...\n\n"
+  fi
+  IFS=$IFS_DEF
+}
+
+show_main_menu()
+{
+  whiptail $MAIN_MENU_BG_COLOR --clear --title "$MAIN_MENU_TITLE" \
+    --menu "$date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
+    'y' ' Default boot' \
+    'r' ' Refresh TOTP/HOTP' \
+    'a' ' Options -->' \
+    'S' ' System Info' \
+    'P' ' Power Off' \
+    2>/tmp/whiptail || recovery "GUI menu failed"
+
+  totp_confirm=$(cat /tmp/whiptail)
+}
+
+show_options_menu()
+{
+  whiptail --clear --title "HEADS Options" \
+    --menu "" 20 90 10 \
+    'o' ' Boot Options -->' \
+    't' ' TPM/TOTP/HOTP Options -->' \
+    's' ' Update checksums and sign all files in /boot' \
+    'c' ' Change configuration settings -->' \
+    'f' ' Flash/Update the BIOS -->' \
+    'G' ' GPG Options -->' \
+    'F' ' OEM Factory Reset -->' \
+    'x' ' Exit to recovery shell' \
+    'r' ' <-- Return to main menu' \
+    2>/tmp/whiptail || recovery "GUI menu failed"
+
+  totp_confirm=$(cat /tmp/whiptail)
+}
+
+show_boot_options_menu()
+{
+  whiptail --clear --title "Boot Options" \
+    --menu "Select A Boot Option" 20 90 10 \
+    'm' ' Show OS boot menu' \
+    'u' ' USB boot' \
+    'i' ' Ignore tampering and force a boot (Unsafe!)' \
+    'r' ' <-- Return to main menu' \
+    2>/tmp/whiptail || recovery "GUI menu failed"
+
+  totp_confirm=$(cat /tmp/whiptail)
+}
+
+show_tpm_totp_hotp_options_menu()
+{
+  whiptail --clear --title "TPM/TOTP/HOTP Options" \
+    --menu "Select An Option" 20 90 10 \
+    'g' ' Generate new TOTP/HOTP secret' \
+    'p' ' Reset the TPM' \
+    'n' ' TOTP/HOTP does not match after refresh, troubleshoot' \
+    'r' ' <-- Return to main menu' \
+    2>/tmp/whiptail || recovery "GUI menu failed"
+
+  totp_confirm=$(cat /tmp/whiptail)
+}
+
+prompt_totp_mismatch()
+{
+  if (whiptail $BG_COLOR_WARNING --title "TOTP/HOTP code mismatched" \
+    --yesno "TOTP/HOTP code mismatches could indicate either TPM tampering or clock drift:\n\nTo correct clock drift: 'date -s HH:MM:SS'\nand save it to the RTC: 'hwclock -w'\nthen reboot and try again.\n\nWould you like to exit to a recovery console?" 30 90) then
+    echo ""
+    echo "To correct clock drift: 'date -s HH:MM:SS'"
+    echo "and save it to the RTC: 'hwclock -w'"
+    echo "then reboot and try again"
+    echo ""
+    recovery "TOTP/HOTP mismatch"
+  fi
+}
+
+reset_tpm()
+{
+  if [ "$CONFIG_TPM" = "y" ]; then
+    if (whiptail --title 'Reset the TPM' \
+        --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
+      /bin/tpm-reset
+
+      # now that the TPM is reset, remove invalid TPM counter files
+      mount_boot
+      mount -o rw,remount /boot
+      rm -f /boot/kexec_rollback.txt
+
+      # create Heads TPM counter before any others
+      check_tpm_counter /boot/kexec_rollback.txt \
+      || die "Unable to find/create tpm counter"
+      counter="$TPM_COUNTER"
+
+      increment_tpm_counter $counter \
+      || die "Unable to increment tpm counter"
+
+      sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
+      || die "Unable to create rollback file"
+      mount -o ro,remount /boot
+
+      generate_totp_htop
+    else
+      echo "Returning to the main menu"
+    fi
+  else
+    whiptail --clear --title 'ERROR: No TPM Detected' --msgbox "This device does not have a TPM.\n\nPress OK to return to the Main Menu" 30 90
+  fi
+}
+
+show_system_info()
+{
+  memtotal=$(cat /proc/meminfo | grep 'MemTotal' | tr -s ' ' | cut -f2 -d ' ')
+  memtotal=$((${memtotal} / 1024 / 1024 + 1))
+  cpustr=$(cat /proc/cpuinfo | grep 'model name' | uniq | sed -r 's/\(R\)//;s/\(TM\)//;s/CPU //;s/model name.*: //')
+  kernel=$(uname -s -r)
+  whiptail --title 'System Info' \
+    --msgbox "${BOARD_NAME}\n\nFW_VER: ${FW_VER}\nKernel: ${kernel}\n\nCPU: ${cpustr}\nRAM: ${memtotal} GB\n\n$(fdisk -l | grep -e '/dev/sd.:' -e '/dev/nvme.*:' | sed 's/B,.*/B/')" 16 60
+}
+
+select_os_boot_option()
+{
+  mount_boot
+  if verify_global_hashes ; then
+    kexec-select-boot -m -b /boot -c "grub.cfg" -g
+  fi
+}
+
+attempt_default_boot()
+{
+  mount_boot
+    
+  if ! verify_global_hashes; then
+    return
+  fi
+  DEFAULT_FILE=`find /boot/kexec_default.*.txt 2>/dev/null | head -1`
+  if [ -r "$DEFAULT_FILE" ]; then
+    kexec-select-boot -b /boot -c "grub.cfg" -g \
+    || recovery "Failed default boot"
+  elif (whiptail --title 'No Default Boot Option Configured' \
+        --yesno "There is no default boot option configured yet.\nWould you like to load a menu of boot options?\nOtherwise you will return to the main menu." 16 90) then
+    kexec-select-boot -m -b /boot -c "grub.cfg" -g
+  fi
+}
+
+force_unsafe_boot()
+{
+  # Run the menu selection in "force" mode, bypassing hash checks
+  if (whiptail $BG_COLOR_WARNING --title 'Unsafe Forced Boot Selected!' \
+      --yesno "WARNING: You have chosen to skip all tamper checks and boot anyway.\n\nThis is an unsafe option!\n\nDo you want to proceed?" 16 90) then
+    mount_boot && kexec-select-boot -m -b /boot -c "grub.cfg" -g -f
+  fi
+}
+
+# gui-init start
+
 if detect_boot_device ; then
   # /boot device with installed OS found
   clean_boot_check
@@ -174,145 +417,36 @@ while true; do
   MAIN_MENU_OPTIONS=""
   MAIN_MENU_BG_COLOR=""
   unset totp_confirm
+
   # detect whether any GPG keys exist in the keyring, if not, initialize that first
-  GPG_KEY_COUNT=`gpg -k 2>/dev/null | wc -l`
-  if [ $GPG_KEY_COUNT -eq 0 ]; then
-    whiptail $BG_COLOR_ERROR --clear --title "ERROR: GPG keyring empty!" \
-      --menu "ERROR: Heads couldn't find any GPG keys in your keyring.\n\nIf this is the first time the system has booted,\nyou should add a public GPG key to the BIOS now.\n\nIf you just reflashed a new BIOS, you'll need to add at least one\npublic key to the keyring.\n\nIf you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n\nHow would you like to proceed?" 30 90 4 \
-      'G' ' Add a GPG key to the running BIOS' \
-      'i' ' Ignore error and continue to main menu' \
-      'x' ' Exit to recovery shell' \
-      2>/tmp/whiptail || recovery "GUI menu failed"
+  check_gpg_key
 
-      totp_confirm=$(cat /tmp/whiptail)
-  fi
   if [ "$totp_confirm" = "i" -o -z "$totp_confirm" ]; then
-    # update the TOTP code every thirty seconds
-    date=`date "+%Y-%m-%d %H:%M:%S"`
-    seconds=`date "+%s"`
-    half=`expr \( $seconds % 60 \) / 30`
-    if [ "$CONFIG_TPM" = n ]; then
-      TOTP="NO TPM"
-    elif [ "$half" != "$last_half" ]; then
-      last_half=$half;
-      TOTP=`unseal-totp`
-      if [ $? -ne 0 ]; then
-        whiptail $BG_COLOR_ERROR --clear --title "ERROR: TOTP Generation Failed!" \
-          --menu "    ERROR: Heads couldn't generate the TOTP code.\n
-    If you have just completed a Factory Reset, or just reflashed
-    your BIOS, you should generate a new HOTP/TOTP secret.\n
-    If this is the first time the system has booted, you should
-    reset the TPM and set your own password.\n
-    If you have not just reflashed your BIOS, THIS COULD INDICATE TAMPERING!\n
-    How would you like to proceed?" 30 90 4 \
-          'g' ' Generate new HOTP/TOTP secret' \
-          'i' ' Ignore error and continue to main menu' \
-          'p' ' Reset the TPM' \
-          'x' ' Exit to recovery shell' \
-          2>/tmp/whiptail || recovery "GUI menu failed"
-
-        totp_confirm=$(cat /tmp/whiptail)
-      fi
-    fi
+    update_totp
   fi
 
   if [ "$totp_confirm" = "i" -o -z "$totp_confirm" ]; then 
-    if [ -x /bin/hotp_verification ]; then
-      HOTP=`unseal-hotp`
-      enable_usb
-      if ! hotp_verification info ; then
-        whiptail $BG_COLOR_WARNING --clear \
-	--title "WARNING: Please Insert Your $HOTPKEY_BRANDING" \
-	--msgbox "Your $HOTPKEY_BRANDING was not detected.\n\nPlease insert your $HOTPKEY_BRANDING" 30 90
-        fi
-      # Don't output HOTP codes to screen, so as to make replay attacks harder
-      hotp_verification check $HOTP
-      case "$?" in
-        0 )
-          HOTP="Success"
-        ;;
-        4 )
-          HOTP="Invalid code"
-          MAIN_MENU_BG_COLOR=$BG_COLOR_ERROR
-        ;;
-        * )
-          HOTP="Error checking code, Insert $HOTPKEY_BRANDING and retry"
-          MAIN_MENU_BG_COLOR=$BG_COLOR_WARNING
-        ;;
-      esac
-    else
-      HOTP='N/A'
-    fi
+    update_hotp
 
     if [[ "$HOTP" = "Success" && $CONFIG_AUTO_BOOT_TIMEOUT && $first_pass = true ]]; then 
-      # save IFS before changing, restore after read
-      IFS_DEF=$IFS
-      IFS=''
-      first_pass=false
-      echo -e "\nHOTP verification success\n\n"
-      read -t $CONFIG_AUTO_BOOT_TIMEOUT -s -n 1 -p "Automatic boot in $CONFIG_AUTO_BOOT_TIMEOUT seconds unless interrupted by keypress... "
-      if [[ $? -ne 0 ]]; then
-        IFS=$IFS_DEF
-        # skip to default boot
-        totp_confirm='y'
-        echo -e "\n\nAttempting default boot...\n\n"
-      fi
-      IFS=$IFS_DEF
+      prompt_auto_default_boot
     fi
 
     if [ "$totp_confirm" != "y" -o -z "$totp_confirm" ]; then
-      whiptail $MAIN_MENU_BG_COLOR --clear --title "$MAIN_MENU_TITLE" \
-        --menu "$date\nTOTP: $TOTP | HOTP: $HOTP" 20 90 10 \
-        'y' ' Default boot' \
-        'r' ' Refresh TOTP/HOTP' \
-        'a' ' Options -->' \
-        'S' ' System Info' \
-        'P' ' Power Off' \
-        2>/tmp/whiptail || recovery "GUI menu failed"
-
-      totp_confirm=$(cat /tmp/whiptail)
+      show_main_menu
     fi
   fi
 
   if [ "$totp_confirm" = "a" ]; then
-    whiptail --clear --title "HEADS Options" \
-      --menu "" 20 90 10 \
-      'o' ' Boot Options -->' \
-      't' ' TPM/TOTP/HOTP Options -->' \
-      's' ' Update checksums and sign all files in /boot' \
-      'c' ' Change configuration settings -->' \
-      'f' ' Flash/Update the BIOS -->' \
-      'G' ' GPG Options -->' \
-      'F' ' OEM Factory Reset -->' \
-      'x' ' Exit to recovery shell' \
-      'r' ' <-- Return to main menu' \
-      2>/tmp/whiptail || recovery "GUI menu failed"
-
-    totp_confirm=$(cat /tmp/whiptail)
+    show_options_menu
   fi
 
   if [ "$totp_confirm" = "o" ]; then
-    whiptail --clear --title "Boot Options" \
-      --menu "Select A Boot Option" 20 90 10 \
-      'm' ' Show OS boot menu' \
-      'u' ' USB boot' \
-      'i' ' Ignore tampering and force a boot (Unsafe!)' \
-      'r' ' <-- Return to main menu' \
-      2>/tmp/whiptail || recovery "GUI menu failed"
-
-    totp_confirm=$(cat /tmp/whiptail)
+    show_boot_options_menu
   fi
 
   if [ "$totp_confirm" = "t" ]; then
-    whiptail --clear --title "TPM/TOTP/HOTP Options" \
-      --menu "Select An Option" 20 90 10 \
-      'g' ' Generate new TOTP/HOTP secret' \
-      'p' ' Reset the TPM' \
-      'n' ' TOTP/HOTP does not match after refresh, troubleshoot' \
-      'r' ' <-- Return to main menu' \
-      2>/tmp/whiptail || recovery "GUI menu failed"
-
-    totp_confirm=$(cat /tmp/whiptail)
+    show_tpm_totp_hotp_options_menu
   fi
 
   if [ "$totp_confirm" = "x" ]; then
@@ -324,17 +458,8 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "n" ]; then
-    if (whiptail $BG_COLOR_WARNING --title "TOTP/HOTP code mismatched" \
-      --yesno "TOTP/HOTP code mismatches could indicate either TPM tampering or clock drift:\n\nTo correct clock drift: 'date -s HH:MM:SS'\nand save it to the RTC: 'hwclock -w'\nthen reboot and try again.\n\nWould you like to exit to a recovery console?" 30 90) then
-      echo ""
-      echo "To correct clock drift: 'date -s HH:MM:SS'"
-      echo "and save it to the RTC: 'hwclock -w'"
-      echo "then reboot and try again"
-      echo ""
-      recovery "TOTP/HOTP mismatch"
-    else
-      continue
-    fi
+    prompt_totp_mismatch
+    continue
   fi
 
   if [ "$totp_confirm" = "u" ]; then
@@ -353,58 +478,18 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "p" ]; then
-    if [ "$CONFIG_TPM" = "y" ]; then
-      if (whiptail --title 'Reset the TPM' \
-          --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
-        /bin/tpm-reset
-
-        # now that the TPM is reset, remove invalid TPM counter files
-        mount_boot
-        mount -o rw,remount /boot
-        rm -f /boot/kexec_rollback.txt
-
-        # create Heads TPM counter before any others
-        check_tpm_counter /boot/kexec_rollback.txt \
-        || die "Unable to find/create tpm counter"
-        counter="$TPM_COUNTER"
-
-        increment_tpm_counter $counter \
-        || die "Unable to increment tpm counter"
-
-        sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
-        || die "Unable to create rollback file"
-        mount -o ro,remount /boot
-
-        generate_totp_htop
-      else
-        echo "Returning to the main menu"
-      fi
-    else
-      whiptail --clear --title 'ERROR: No TPM Detected' --msgbox "This device does not have a TPM.\n\nPress OK to return to the Main Menu" 30 90
-    fi
+    reset_tpm
     continue
   fi
 
   if [ "$totp_confirm" = "m" ]; then
     # Try to select a kernel from the menu
-    mount_boot
-    verify_global_hashes
-    if [ $? -ne 0 ]; then
-      continue
-    fi
-    kexec-select-boot -m -b /boot -c "grub.cfg" -g
+    select_os_boot_option
     continue
   fi
 
   if [ "$totp_confirm" = "i" ]; then
-    # Run the menu selection in "force" mode, bypassing hash checks
-    if (whiptail $BG_COLOR_WARNING --title 'Unsafe Forced Boot Selected!' \
-        --yesno "WARNING: You have chosen to skip all tamper checks and boot anyway.\n\nThis is an unsafe option!\n\nDo you want to proceed?" 16 90) then
-      mount_boot
-      kexec-select-boot -m -b /boot -c "grub.cfg" -g -f
-    else
-      echo "Returning to the main menu"
-    fi
+    force_unsafe_boot
     continue
   fi
 
@@ -429,12 +514,7 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "S" ]; then
-    memtotal=$(cat /proc/meminfo | grep 'MemTotal' | tr -s ' ' | cut -f2 -d ' ')
-    memtotal=$((${memtotal} / 1024 / 1024 + 1))
-    cpustr=$(cat /proc/cpuinfo | grep 'model name' | uniq | sed -r 's/\(R\)//;s/\(TM\)//;s/CPU //;s/model name.*: //')
-    kernel=$(uname -s -r)
-		whiptail --title 'System Info' \
-      --msgbox "${BOARD_NAME}\n\nFW_VER: ${FW_VER}\nKernel: ${kernel}\n\nCPU: ${cpustr}\nRAM: ${memtotal} GB\n\n$(fdisk -l | grep -e '/dev/sd.:' -e '/dev/nvme.*:' | sed 's/B,.*/B/')" 16 60
+    show_system_info
     continue
   fi
 
@@ -449,24 +529,7 @@ while true; do
 
   if [ "$totp_confirm" = "y" -o -n "$totp_confirm" ]; then
     # Try to boot the default
-    mount_boot
-    verify_global_hashes
-    if [ $? -ne 0 ]; then
-      continue
-    fi
-    DEFAULT_FILE=`find /boot/kexec_default.*.txt 2>/dev/null | head -1`
-    if [ -r "$DEFAULT_FILE" ]; then
-      kexec-select-boot -b /boot -c "grub.cfg" -g \
-      || recovery "Failed default boot"
-    else
-      if (whiptail --title 'No Default Boot Option Configured' \
-          --yesno "There is no default boot option configured yet.\nWould you like to load a menu of boot options?\nOtherwise you will return to the main menu." 16 90) then
-        kexec-select-boot -m -b /boot -c "grub.cfg" -g
-      else
-        echo "Returning to the main menu"
-      fi
-      continue
-    fi
+    attempt_default_boot
   fi
 
 done
