WiP: done testing LUKS passphrase for Q4.2.1 BTRFS deployment(multiple LUKS containers scenario), cleanup keyslot-> key slot everywhere
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -11,7 +11,7 @@ find_drk_key_slot() {
 
 	for keyslot in "${luks_used_keyslots[@]}"; do
 		if [ -z "$temp_drk_key_slot" ]; then
-			DEBUG "Testing LUKS key-slot $keyslot against $DISK_RECOVERY_KEY_FILE for Disk Recovery Key slot..."
+			DEBUG "Testing LUKS key slot $keyslot against $DISK_RECOVERY_KEY_FILE for Disk Recovery Key slot..."
 			if DO_WITH_DEBUG cryptsetup open --test-passphrase --key-slot "$keyslot" --key-file "$DISK_RECOVERY_KEY_FILE" "$dev"; then
 				temp_drk_key_slot="$keyslot"
 				DEBUG "Disk Recovery key slot is $temp_drk_key_slot"
@@ -41,11 +41,12 @@ fi
 
 KEY_DEVICES="$paramsdir/kexec_key_devices.txt"
 KEY_LVM="$paramsdir/kexec_key_lvm.txt"
+key_devices=$(cat "$KEY_DEVICES" | cut -d\  -f1 | tr '\n' ' ')
 
 if [ ! -r "$KEY_DEVICES" ]; then
 	die "No devices defined for disk encryption"
 else
-	DEBUG "Devices defined for disk encryption: $(cat "$KEY_DEVICES" | cut -d\  -f1 | tr '\n' ' ')"
+	DEBUG "Devices defined for disk encryption: $key_devices"
 fi
 
 if [ -r "$KEY_LVM" ]; then
@@ -62,23 +63,33 @@ fi
 
 DEBUG "$(pcrs)"
 
-for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
+
+luks_drk_passphrase_valid=0
+for dev in $key_devices	; do
 	attempts=0
 	while [ $attempts -lt 3 ]; do
-		read -s -p "Enter LUKS Disk Recovery Key (DRK) passphrase for $dev: " disk_password
-		echo -n "$disk_password" >"$DISK_RECOVERY_KEY_FILE"
-		echo
+		if [ "$luks_drk_passphrase_valid" == "0" ]; then
+			# Ask for the passphrase only once
+			read -s -p "Enter LUKS Disk Recovery Key (DRK) passphrase that can unlock: $key_devices: " disk_recovery_key_passphrase
+			#Using he provided passphrase as the DRK "keyfile" for unattended operations
+			echo -n "$disk_recovery_key_passphrase" >"$DISK_RECOVERY_KEY_FILE"
+			echo
+		fi
 
-		DEBUG "Testing $DISK_RECOVERY_KEY_FILE keyfile created from provided passphrase against $dev"
+		DEBUG "Testing $DISK_RECOVERY_KEY_FILE keyfile created from provided passphrase against $dev individual key slots"
 		if cryptsetup open $dev --test-passphrase --key-file "$DISK_RECOVERY_KEY_FILE" >/dev/null 2>&1; then
 			DEBUG "LUKS device $dev unlocked successfully with the DRK passphrase"
+			luks_drk_passphrase_valid=1
 			break
 		else
 			attempts=$((attempts + 1))
-			if [ "$attempts" == "3" ]; then
+			if [ "$attempts" == "3" ] && [ "$luks_drk_passphrase_valid" == "0" ]; then
 				die "Failed to unlock LUKS device $dev with the provided passphrase. Exiting..."
+			elif [ "$attempts" != "3" ] && [ "$luks_drk_passphrase_valid" == "1" ]; then
+				#We failed unlocking with DRK passphrase another LUKS container
+				die "LUKS device $key_devices cannot all be unlocked with same passphrase. Please make $key_devices devices unlockable with the same passphrase. Exiting"
 			else
-				echo "Incorrect passphrase. Please try again."
+				warn "Failed to unlock LUKS device $dev with the provided passphrase. Please try again."
 			fi
 		fi
 	done
@@ -95,7 +106,7 @@ while [ $attempts -lt 3 ]; do
 		if [ "$attempts" == "3" ]; then
 			die "Disk Unlock Key passphrases do not match. Exiting..."
 		else
-			echo "Disk Unlock Key passphrases do not match. Please try again."
+			warn "Disk Unlock Key passphrases do not match. Please try again."
 		fi
 	else
 		break
@@ -113,7 +124,7 @@ dd \
 	die "Unable to generate 128 random bytes"
 
 previous_luks_header_version=0
-for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
+for dev in $key_devices; do
 	# Check and store LUKS version of the devices to be used later
 	luks_version=$(cryptsetup luksDump "$dev" | grep "Version" | cut -d: -f2 | tr -d '[:space:]')
 	if [ "$luks_version" == "2" ] && [ "$previous_luks_header_version" == "1" ]; then
@@ -125,14 +136,14 @@ for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
 	fi
 
 	if [ "$luks_version" == "2" ]; then
-		# keyslot is the last slot for LUKSv2 which is 31
+		# LUKSv2 last key slot is 31
 		duk_keyslot=31
 		regex="^\s+([0-9]+):\s*luks2"
 		sed_command="s/^\s\+\([0-9]\+\):\s*luks2/\1/g"
 		previous_luks_header_version=2
 		DEBUG "$dev: LUKSv2 device detected"
 	elif [ "$luks_version" == "1" ]; then
-		# keyslot is the last slot for LUKSv1 which is 7
+		# LUKSv1 last key slot is 7
 		duk_keyslot=7
 		regex="Key Slot ([0-9]+): ENABLED"
 		sed_command='s/Key Slot \([0-9]\+\): ENABLED/\1/'
@@ -165,11 +176,11 @@ for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
 
 			if [ "$keyslot" != "$drk_key_slot" ] && [ "$keyslot" == "1" ]; then
 				wipe_desired="yes"
-				DEBUG "LUKS keyslot $keyslot not DRK. Will wipe this DUK keyslot silently"
+				DEBUG "LUKS key slot $keyslot not DRK. Will wipe this DUK key slot silently"
 			elif [ "$keyslot" != "$drk_key_slot" ] && [ "$keyslot" != "$duk_keyslot" ]; then
-				# Heads expects key-slot LUKSv1:7 or LUKSv2:31 to be used for TPM DUK setup.
+				# Heads expects key slot LUKSv1:7 or LUKSv2:31 to be used for TPM DUK setup.
 				#  Ask user to confirm otherwise
-				wan "LUKS key-slot $keyslot is not typical ($duk_keyslot expected) for TPM Disk Unlock Key setup"
+				warn "LUKS key slot $keyslot is not typical ($duk_keyslot expected) for TPM Disk Unlock Key setup"
 				read -p "Are you sure you want to wipe it? [y/N] " -n 1 -r
 				echo
 				# If user does not confirm, skip this slot
@@ -177,13 +188,13 @@ for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
 					wipe_desired="yes"
 				fi
 			elif [ "$keyslot" == "$duk_keyslot" ]; then
-				# If keyslot is the expected DUK keyslot, we wipe it silently
-				DEBUG "LUKS keyslot $keyslot is the expected DUK keyslot. Will wipe this DUK keyslot silently"
+				# If key slot is the expected DUK keyslot, we wipe it silently
+				DEBUG "LUKS key slot $keyslot is the expected DUK key slot. Will wipe this DUK key slot silently"
 				wipe_desired="yes"
 			fi
 
 			if [ "$wipe_desired" == "yes" ] && [ "$keyslot" != "$drk_key_slot" ]; then
-				echo "++++++ $dev: Wiping LUKS key-slot $keyslot"
+				echo "++++++ $dev: Wiping LUKS key slot $keyslot"
 				DO_WITH_DEBUG cryptsetup luksKillSlot \
 					--key-file "$DISK_RECOVERY_KEY_FILE" \
 					$dev $keyslot ||
@@ -193,19 +204,19 @@ for dev in $(cat "$KEY_DEVICES" | cut -d\  -f1); do
 	done
 
 
-	echo "++++++ $dev: Adding LUKS TPM Disk Unlock Key to LUKS key-slot $duk_keyslot"
+	echo "++++++ $dev: Adding LUKS TPM Disk Unlock Key to LUKS key slot $duk_keyslot"
 	DO_WITH_DEBUG cryptsetup luksAddKey \
 		--key-file "$DISK_RECOVERY_KEY_FILE" \
 		--new-key-slot $duk_keyslot \
 		$dev "$DUK_KEY_FILE" ||
-		die "$dev: Unable to add LUKS TPM Disk Unlock Key to LUKS key-slot $duk_keyslot"
+		die "$dev: Unable to add LUKS TPM Disk Unlock Key to LUKS key slot $duk_keyslot"
 done
 
 # Now that we have setup the new keys, measure the PCRs
 # We don't care what ends up in PCR 6; we just want
 # to get the /tmp/luksDump.txt file.  We use PCR16
 # since it should still be zero
-cat "$KEY_DEVICES" | cut -d\  -f1 | xargs /bin/qubes-measure-luks ||
+echo "$key_devices" | xargs /bin/qubes-measure-luks ||
 	die "Unable to measure the LUKS headers"
 
 pcrf="/tmp/secret/pcrf.bin"
