TPM disk unlock key setup: Automatically override selected default boot option's initrd's crypttab file(s) to point to LUKS decryption key in injected cpio - kexec-save-default extracts initrd crypttab files and creates /boot/kexec_initrd_crypttab_overrides.txt entries pointing to /secret.key - kexec-insert-key applies /boot/kexec_initrd_crypttab_overrides.txt to replace initrd's crypttabs files pointing to inserted /secret.key through cpio - Both scripts inform the user of applied magic on screen

diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -129,6 +129,52 @@ if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
 	die "Failed to write default config"
 fi
 
+if [ "$save_key" = "y" ]; then
+	# logic to parse OS initrd to extract crypttab, its filepaths and its OS defined options
+	mkdir -p /tmp/initrd_extract
+	cd /tmp/initrd_extract
+	# Get initrd filename selected to be default initrd that OS could be using to configure LUKS on boot by deploying crypttab files
+	current_default_initrd=$(cat /boot/kexec_default_hashes.txt | grep initr | awk -F " " {'print $NF'} | sed 's/\.\//\/boot\//g')
+	
+	# Get crypttab files paths from initrd
+	echo "Checking current selected default boot's $current_default_initrd for existing crypttab files..."
+	# First either decompress or use the original if it's not compressed
+	initrd_decompressed="/tmp/initrd_extract/initrd_decompressed.cpio"
+	zcat < "$current_default_initrd" > "$initrd_decompressed" 2> /dev/null || initrd_decompressed="$current_default_initrd"
+	crypttab_files=$(cpio --list --quiet < "$initrd_decompressed" | grep crypttab 2> /dev/null) || true
+	
+	if [ ! -z "$crypttab_files" ]; then
+		echo "Extracting current selected default boot's $current_default_initrd for found crypttab files analysis..."
+		cpio -id --quiet < $initrd_decompressed $crypttab_files 2> /dev/null
+		rm -f $bootdir/kexec_initrd_crypttab_overrides.txt || true
+		
+		#Parsing each crypttab file found
+		echo "$crypttab_files" | while read filepath; do
+			# Keep only non-commented lines
+			current_filepath_entries=$(cat "$filepath" | grep -v "^#")
+			# Modify each retained crypttab line to contain to be injected /secret.key at next default boots
+			modified_filepath_entries=$(echo "$current_filepath_entries" | sed 's/none/\/secret.key/g')
+			echo "$modified_filepath_entries" | while read single_modified_filepath_entry; do
+				# Append each found filepath:entry into additional kexec_ file that will be part of detached signed digest
+				echo "$filepath:$single_modified_filepath_entry" >> $bootdir/kexec_initrd_crypttab_overrides.txt
+			done
+		done
+
+		cd - > /dev/null
+
+		#insert current default boot's initrd crypttab locations into tracking file to be overwritten into initramfs at kexec-inject-key
+		echo "The following OS crypttab file:entry were modified from default boot's initrd:"
+		cat $bootdir/kexec_initrd_crypttab_overrides.txt
+		echo "Heads added /secret.key in those entries and saved them under $bootdir/kexec_initrd_crypttab_overrides.txt"
+		echo "Those overrides will be part of detached signed digests and used to prepare cpio injected at kexec of selected default boot entry."
+	else
+		echo "No crypttab file found in extracted initrd. Removing $bootdir/kexec_initrd_crypttab_overrides.txt"
+		rm -f "$bootdir/kexec_initrd_crypttab_overrides.txt" || true
+	fi
+	# Cleanup
+	rm -rf /tmp/initrd_extract || true
+fi
+
 # sign and auto-roll config counter
 extparam=
 if [ "$CONFIG_TPM" = "y" ]; then
