Added rollback protection to generic boot
Changed the checking of required hashes or required rollback state
to be right before boot, allowing the user to sign/set defaults
in interactive mode.

Also cleaned up usages of recovery and fixed iso parameter
regression.
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -7,13 +7,12 @@ while getopts "b:d:p:e:i:" arg; do
 		b) bootdir="$OPTARG" ;;
 		d) paramsdev="$OPTARG" ;;
 		p) paramsdir="$OPTARG" ;;
-		e) entry="$OPTARG" ;;
 		i) index="$OPTARG" ;;
 	esac
 done
 
-if [ -z "$bootdir" -o -z "$entry" -o -z "$index" ]; then
-	die "Usage: $0 -b /boot/ -e \"boot params|...\" -i 1 "
+if [ -z "$bootdir" -o -z "$index" ]; then
+	die "Usage: $0 -b /boot/ -i menu_option "
 fi
 
 if [ -z "$paramsdev" ]; then
@@ -24,14 +23,25 @@ if [ -z "$paramsdir" ]; then
 	paramsdir="$bootdir"
 fi
 
+TMP_MENU_FILE="/tmp/kexec/kexec_menu.txt"
 ENTRY_FILE="$paramsdir/kexec_default.$index.txt"
 HASH_FILE="$paramsdir/kexec_default_hashes.txt"
+
+if [ ! -r "$TMP_MENU_FILE" ]; then
+	die "No menu options available, please run kexec-select-boot"
+fi
+
+entry=`head -n $index $TMP_MENU_FILE | tail -1`
+if [ -z "$entry" ]; then
+	die "Invalid menu index $index"
+fi
 
 # try to switch to rw mode
 mount -o rw,remount $paramsdev
 
 if [ ! -d $paramsdir ]; then
-	mkdir -p $paramsdir
+	mkdir -p $paramsdir \
+	|| die "Failed to create params directory"
 fi
 rm "$paramsdir/kexec_default.*.txt" 2>/dev/null
 echo "$entry" > $ENTRY_FILE
@@ -40,9 +50,9 @@ if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
 	die "Failed to write default config"
 fi
 
-if ! kexec-sign-config $paramsdir; then
-	die "Failed to sign default config"
-fi
+# sign and auto-roll config counter
+kexec-sign-config -p $paramsdir -u \
+|| die "Failed to sign default config"
 
 # switch back to ro mode
 mount -o ro,remount $paramsdev
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -88,3 +88,67 @@ confirm_gpg_card()
 	gpg --card-status \
 	|| die "gpg card read failed"
 }
+
+
+check_tpm_counter()
+{
+	# if the /boot.hashes file already exists, read the TPM counter ID
+	# from it.
+	if [ -r "$1" ]; then
+		TPM_COUNTER=`grep counter- "$1" | cut -d- -f2`
+	else
+		warn "$BOOT_HASHES does not exist; creating new TPM counter"
+		read -s -p "TPM Owner password: " tpm_password
+		echo
+		tpm counter_create \
+			-pwdo "$tpm_password" \
+			-pwdc '' \
+			-la 3135106223 \
+		| tee /tmp/counter \
+		|| die "Unable to create TPM counter"
+		TPM_COUNTER=`cut -d: -f1 < /tmp/counter`
+	fi
+
+	if [ -z "$TPM_COUNTER" ]; then
+		die "$1: TPM Counter not found?"
+	fi
+}
+
+read_tpm_counter()
+{
+	tpm counter_read -ix "$1" | tee "/tmp/counter-$1" \
+	|| die "Counter read failed"
+}
+
+increment_tpm_counter()
+{
+	tpm counter_increment -ix "$1" -pwdc '' \
+		| tee /tmp/counter-$1 \
+	|| die "Counter increment failed"
+}
+
+check_config() {
+	if [ ! -d /tmp/kexec ]; then
+		mkdir /tmp/kexec \
+		|| die 'Failed to make kexec tmp dir'
+	else
+		rm -rf /tmp/kexec/* \
+		|| die 'Failed to empty kexec tmp dir'
+	fi
+
+	if [ ! -r $1/kexec.sig ]; then
+		return
+	fi
+
+	if [ `find $1/kexec*.txt | wc -l` -eq 0 ]; then
+		return
+	fi
+
+	if ! sha256sum `find $1/kexec*.txt` | gpgv $1/kexec.sig - ; then
+		die 'Invalid signature on kexec boot params'
+	fi
+
+	echo "+++ Found verified kexec boot params"
+	cp $1/kexec*.txt /tmp/kexec \
+	|| die "Failed to copy kexec boot params to tmp"
+}
