Add PureBoot Basic Mode
PureBoot Basic mode provides the full Linux userspace in firmware from
Heads without requiring verified boot or a Librem Key.  Basic and
verified boot can be switched freely without changing firmware, such as
if a Librem Key is lost.

PureBoot Basic can apply firmware updates from a USB flash drive, and
having a complete Linux userspace enables more sophisticated recovery
options.

Basic mode boots to the first boot option by default, setting a default
is not required.  This can be configured in the config GUI.

Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>

diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -257,19 +257,20 @@ default_select() {
 	fi
 	parse_option
 
-	# Enforce that default option hashes are valid
-	echo "+++ Checking verified default boot hash file "
-	# Check the hashes of all the files
-	if ( cd $bootdir && sha256sum -c "$TMP_DEFAULT_HASH_FILE" > /tmp/hash_output ); then
-		echo "+++ Verified default boot hashes "
-		valid_hash='y'
-	else
-		if [ "$gui_menu" = "y" ]; then
-			CHANGED_FILES=$(grep -v 'OK$' /tmp/hash_output | cut -f1 -d ':')
-			whiptail $BG_COLOR_ERROR --title 'ERROR: Default Boot Hash Mismatch' \
-				--msgbox "The following files failed the verification process:\n${CHANGED_FILES}\nExiting to a recovery shell" 0 80
+	if [ "$CONFIG_PUREBOOT_BASIC" != "y" ]; then
+		# Enforce that default option hashes are valid
+		echo "+++ Checking verified default boot hash file "
+		# Check the hashes of all the files
+		if ( cd $bootdir && sha256sum -c "$TMP_DEFAULT_HASH_FILE" > /tmp/hash_output ); then
+			echo "+++ Verified default boot hashes "
+			valid_hash='y'
+		else
+			if [ "$gui_menu" = "y" ]; then
+				CHANGED_FILES=$(grep -v 'OK$' /tmp/hash_output | cut -f1 -d ':')
+				whiptail $BG_COLOR_ERROR --title 'ERROR: Default Boot Hash Mismatch' \
+					--msgbox "The following files failed the verification process:\n${CHANGED_FILES}\nExiting to a recovery shell" 0 80
+			fi
 		fi
-		die "!!! $TMP_DEFAULT_HASH_FILE: default boot hash mismatch"
 	fi
 
 	echo "+++ Executing default boot for $name:"
@@ -320,6 +321,11 @@ user_select() {
 
 do_boot()
 {
+	if [ "$CONFIG_PUREBOOT_BASIC" != "y" ]; then
+		kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
+				|| die "!!! Failed to boot w/ options: $option"
+	fi
+
 	if [ "$CONFIG_BOOT_REQ_ROLLBACK" = "y" -a "$valid_rollback" = "n" ]; then
 		die "!!! Missing required rollback counter state"
 	fi
@@ -348,7 +354,7 @@ do_boot()
 }
 
 while true; do
-	if [ "$force_boot" = "y" ]; then
+	if [ "$force_boot" = "y" -o "$CONFIG_PUREBOOT_BASIC" = "y" ]; then
 	  check_config $paramsdir force
 	else
 	  check_config $paramsdir
@@ -366,9 +372,11 @@ while true; do
 # even if hashes don't match
 	if [ "$force_boot" = "y" ]; then
 		scan_options
-		# Remove boot splash and make background red in the event of a forced boot
-		add="$add vt.default_red=0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff"
-		remove="$remove splash quiet"
+		if [ "$CONFIG_PUREBOOT_BASIC" != "y" ]; then
+			# Remove boot splash and make background red in the event of a forced boot
+			add="$add vt.default_red=0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff"
+			remove="$remove splash quiet"
+		fi
 		user_select
 	fi
 
@@ -385,7 +393,7 @@ while true; do
 		scan_options
 	fi
 
-	if [ "$CONFIG_TPM" = "y" ]; then
+	if [ "$CONFIG_TPM" = "y" -a "$CONFIG_PUREBOOT_BASIC" != "y" ]; then
 		# Optionally enforce device file hashes
 		if [ -r "$TMP_HASH_FILE" ]; then
 			valid_global_hash="n"
