Add DEBUG traces and have TPM2 boards enable TRACE and DEBUG calls - /tmp/debug.log is created and appended by all TRACE and DEBUG calls in code - fix some logic errors seen when no DEBUG entry were outputted in /tmp/debug.log

diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -297,8 +297,13 @@ user_select() {
 		else
 			echo "+++ Rebooting to start the new default option"
 			sleep 2
-			reboot \
-			|| die "!!! Failed to reboot system"
+			if [ "$CONFIG_DEBUG_OUTPUT" != "y" ]; then
+				reboot \
+				|| die "!!! Failed to reboot system"
+			else
+				DEBUG "Rebooting is required prior of booting default boot entry"
+				sleep 2
+			fi
 		fi
 	fi
 
