Addition of qemu-(fb)whiptail-tpm2(-hotp) boards -coreboot support of TPM v2.0 (shared config for TPM2 support across all 4 previous variations) -swtpm set to be launched under TPM v2.0 mode under board config -Documentation file under each board.md softlinks to qemu-coreboot-fbwhiptail-tpm1.md (which has been generalized) This is skeleton for TPM v2 integration under Heads
-------------
WiP

TODO:
- libcurl cannot be built as a tpm2-tools dependency as of now not sure why. curl currently needs to be added in board config to be built
- Note: tpm-reset (master and here) needs some review, no handle of no tpm use case. Caller is responsible to not call it otherwise does nothing
- init tries to bind fd and fails currently
- Note: Check if whiptail is different of fbwhiptail in clearing screen. As of now every clear seems to be removed, still whiptail clears previous console output
- When no OS' /boot can be mounted, do not try to TPM reset (will fail)

- seal-hotpkey is not working properly
- setting disk unlock key asks for TPM ownership passphrase (sealing in NV requires ownership, but text is misleading user as if reowning TPM)
  - We should cache input, feed tpm behind the scene and wipe passphrase and state clearly that this is TPM disk unlock kye passphrase.
- primary key from TPM2 is invalid most of the time from kexec-select-boot and verifying global hashes but is setuped correctly at disk unlock key setup
- would be nice to take advantage of bash function tracing to understand where we are for debugging purposes, code takes ash in consideration only
- tpmr says it implements nv calls but actually doesn't. Removing those falsely wrapped functions would help.
  - Implementing them would be better
- REVIEW TODOS IN CODE
- READD CIRCLECI CONFIG

Current state:
- TPM unseal works without disk unlock key and generates TOTP properly (was missing die condition at unseal to not produce always good TOTP even if invalid)
- TPM disk encryption key fails. Hypothesis is that sealing with USB drivers loaded and measures in inconsistent with sealed with/without.
 - TPM disk unsealing happens without USB modules being loaded in non-HOTP setup. This fails.

- Current tests are with fbwhiptail (no clear called so having traces on command line of what happens)
 - Testing with HOTP implementation for sealing/unsealing since that forces USB module loads on each boot to remove this from failing possibilities
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -34,6 +34,7 @@ paramsdir="${paramsdir%%/}"
 TMP_MENU_FILE="/tmp/kexec/kexec_menu.txt"
 ENTRY_FILE="$paramsdir/kexec_default.$index.txt"
 HASH_FILE="$paramsdir/kexec_default_hashes.txt"
+PRIMHASH_FILE="$paramsdir/kexec_primhdl_hash.txt"
 
 if [ ! -r "$TMP_MENU_FILE" ]; then
 	die "No menu options available, please run kexec-select-boot"
@@ -47,7 +48,7 @@ fi
 KEY_DEVICES="$paramsdir/kexec_key_devices.txt"
 KEY_LVM="$paramsdir/kexec_key_lvm.txt"
 save_key="n"
-if [[ "$CONFIG_TPM" = "y" && "$CONFIG_TPM_NO_LUKS_DISK_UNLOCK" != "y" ]]; then
+if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] && [ "$CONFIG_TPM_NO_LUKS_DISK_UNLOCK" != "y" ]; then
 	if [ ! -r "$KEY_DEVICES" ]; then
 		read \
 			-n 1 \
@@ -93,14 +94,14 @@ if [[ "$CONFIG_TPM" = "y" && "$CONFIG_TPM_NO_LUKS_DISK_UNLOCK" != "y" ]]; then
 		lvm vgscan || true
 
 		read \
-			-p "Encrypted LVM group? ($lvm_suggest): " \
+			-p "LVM group containing Encrypted LVs (retype to keep)? ($lvm_suggest): " \
 			lvm_volume_group
 
 		echo "+++ Block devices (blkid): "
 		blkid || true
 
 		read \
-			-p "Encrypted devices? ($devices_suggest): " \
+			-p "Encrypted devices (retype to keep)? ($devices_suggest): " \
 			key_devices
 
 		save_key_params="-s -p $paramsdev"
@@ -122,6 +123,14 @@ if [ ! -d $paramsdir ]; then
 	mkdir -p $paramsdir \
 	|| die "Failed to create params directory"
 fi
+
+if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	if [ ! -r "$PRIMHASH_FILE" ]; then
+		sha256sum /tmp/primary.handle > "$PRIMHASH_FILE" \
+			|| die "ERROR: Failed to Hash TPM2 primary key handle!"
+	fi
+fi
+
 rm $paramsdir/kexec_default.*.txt 2>/dev/null || true
 echo "$entry" > $ENTRY_FILE
 ( cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f| \
@@ -179,8 +188,10 @@ fi
 
 # sign and auto-roll config counter
 extparam=
-if [ "$CONFIG_TPM" = "y" ]; then
-	extparam=-r
+if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ];then
+	if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
+		extparam=-r
+	fi
 fi
 kexec-sign-config -p $paramsdir $extparam \
 || die "Failed to sign default config"
diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -36,20 +36,27 @@ if [ -r "$KEY_LVM" ]; then
 		|| die "$VOLUME_GROUP: unable to activate volume group"
 fi
 
-# Key slot 0 is the manual recovery pass phrase
-# that they user entered when they installed Qubes,
+echo "DEBUG: CONFIG_TPM: $CONFIG_TPM"
+echo "DEBUG: CONFIG_TPM2_TOOLS: $CONFIG_TPM2_TOOLS"
+echo "DEBUG: Show PCRs"
+pcrs
+
+# LUKS Key slot 0 is the manual recovery pass phrase
+# that they user entered when they installed OS,
 # key slot 1 is the one that we've generated.
 read -s -p "Enter disk recovery key: " disk_password
 echo -n "$disk_password" > "$RECOVERY_KEY"
 echo
 
-read -s -p "New disk unlock password for booting: " key_password
-echo
-read -s -p "Repeat unlock code: " key_password2
-echo
+if [ "$CONFIG_AUTO_UNLOCK" != y ]; then
+	read -s -p "New disk unlock password for booting: " key_password
+	echo
+	read -s -p "Repeat unlock code: " key_password2
+	echo
 
-if [ "$key_password" != "$key_password2" ]; then
-	die "Key passwords do not match"
+	if [ "$key_password" != "$key_password2" ]; then
+		die "Key passwords do not match"
+	fi
 fi
 
 # Generate key file
@@ -83,73 +90,138 @@ done
 # since it should still be zero
 cat "$KEY_DEVICES" | cut -d\  -f1 | xargs /bin/qubes-measure-luks \
 	|| die "Unable to measure the LUKS headers"
-luks_pcr=`tpm calcfuturepcr -ix 16 -if /tmp/luksDump.txt`
 
-# HOTP USB Secrity Dongle loads USB modules which changes PCR5.
-# In the event HOTP USB Security Dongle is enabled, skip verification of PCR5
-if [ -x /bin/hotp_verification ]; then
-  pcr_5="X"
-else
-  pcr_5="0000000000000000000000000000000000000000"
-fi
-
-# Note that PCR 4 needs to be set with the "normal-boot"
-# path value, which we do not have right now since we are
-# in a recovery shell.
-# used to be -ix 4 f8fa3b6e32e7c6fe04c366e74636e505b28f3b0d \
-# now just all zeros in a normal boot
-# PCR 5 must be all zero since no kernel modules should have
-# been loaded during a normal boot, but might have been
-# loaded in the recovery shell.
-# Otherwise use the current values of the PCRs, which will be read
-# from the TPM as part of the sealing ("X").
-tpm sealfile2 \
-	-if "$KEY_FILE" \
-	-of "$TPM_SEALED" \
-	-pwdd "$key_password" \
-	-hk 40000000 \
-	-ix 0 X \
-	-ix 1 X \
-	-ix 2 X \
-	-ix 3 X \
-	-ix 4 0000000000000000000000000000000000000000 \
-	-ix 5 $pcr_5 \
-	-ix 6 $luks_pcr \
-	-ix 7 X \
-|| die "Unable to seal secret"
-
-shred -n 10 -z -u "$KEY_FILE" 2> /dev/null \
-|| die "Failed to delete key file"
-
-# try it without the owner password first
-if ! tpm nv_writevalue \
-	-in $TPM_INDEX \
-	-if "$TPM_SEALED" \
-; then
-	# to create an nvram space we need the TPM owner password
-	# and the TPM physical presence must be asserted.
+if [ "$CONFIG_TPM" = "y" ];then
+	luks_pcr=`tpm calcfuturepcr -ix 16 -if /tmp/luksDump.txt`
+	# HOTP USB Secrity Dongle loads USB modules which changes PCR5.
+	# In the event HOTP USB Security Dongle is enabled, skip verification of PCR5
+	# If modules should be loaded during normal boot, skip verification of PCR5
 	#
-	# The permissions are 0 since there is nothing special
-	# about the sealed file
-	tpm physicalpresence -s \
-	|| warn "Warning: Unable to assert physical presence"
+	#TODO: check condition, no libdata.ko
+	if [ "$CONFIG_USB_KEYBOARD" = "y" -o -r /lib/modules/libata.ko -o -x /bin/hotp_verification ]; then
+		pcr_5="X"
+	else
+		pcr_5="0000000000000000000000000000000000000000"
+	fi
 
-	read -s -p "TPM Owner password: " tpm_password
-	echo
+	# Note that PCR 4 needs to be set with the "normal-boot"
+	# path value, which we do not have right now since we are
+	# in a "init" mode
+	# used to be -ix 4 f8fa3b6e32e7c6fe04c366e74636e505b28f3b0d \
+	# now just all zeros in a normal boot
+	# PCR 5 must be all zero since no kernel modules should have
+	# been loaded during a normal boot, but might have been
+	# loaded in the recovery shell.
+	# Otherwise use the current values of the PCRs, which will be read
+	# from the TPM as part of the sealing ("X").
+	if [ "$CONFIG_AUTO_UNLOCK" != y ]; then
+		tpm sealfile2 \
+			-if "$KEY_FILE" \
+			-of "$TPM_SEALED" \
+			-pwdd "$key_password" \
+			-hk 40000000 \
+			-ix 0 X \
+			-ix 1 X \
+			-ix 2 X \
+			-ix 3 X \
+			-ix 4 0000000000000000000000000000000000000000 \
+			-ix 5 $pcr_5 \
+			-ix 6 $luks_pcr \
+			-ix 7 X
+	else
+		tpm sealfile2 \
+			-if "$KEY_FILE" \
+			-of "$TPM_SEALED" \
+			-hk 40000000 \
+			-ix 0 X \
+			-ix 1 X \
+			-ix 2 X \
+			-ix 3 X \
+			-ix 4 0000000000000000000000000000000000000000 \
+			-ix 5 $pcr_5 \
+			-ix 6 $luks_pcr \
+			-ix 7 X
+	fi
 
-	tpm nv_definespace \
-		-in $TPM_INDEX \
-		-sz $TPM_SIZE \
-		-pwdo "$tpm_password" \
-		-per 0 \
-	|| warn "Warning: Unable to define NVRAM space; trying anyway"
+	if [ $? -ne 0 ]; then
+		die "Unable to seal secret"
+	fi
 
+	shred -n 10 -z -u "$KEY_FILE" 2> /dev/null \
+		|| die "Failed to delete key file"
 
-	tpm nv_writevalue \
+	# try it without the owner password first
+	if ! tpm nv_writevalue \
 		-in $TPM_INDEX \
 		-if "$TPM_SEALED" \
-	|| die "Unable to write sealed secret to NVRAM"
+		; then
+		# to create an nvram space we need the TPM owner password
+		# and the TPM physical presence must be asserted.
+		#
+		# The permissions are 0 since there is nothing special
+		# about the sealed file
+		tpm physicalpresence -s \
+			|| warn "Warning: Unable to assert physical presence"
+
+		read -s -p "TPM Owner password: " tpm_password
+		echo
+
+		tpm nv_definespace \
+			-in $TPM_INDEX \
+			-sz $TPM_SIZE \
+			-pwdo "$tpm_password" \
+			-per 0 \
+			|| warn "Warning: Unable to define NVRAM space; trying anyway"
+
+
+		tpm nv_writevalue \
+			-in $TPM_INDEX \
+			-if "$TPM_SEALED" \
+			|| die "Unable to write sealed secret to NVRAM"
+	fi
+elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	pcrf="/tmp/secret/pcrf.bin"
+	#TODO: verify logic below against tpm2
+	tpm2 pcrread -o "$pcrf" sha256:0,1,2,3
+	# pcr 4 is expected to be zero (init mode)
+	dd if=/dev/zero bs=32 count=1 >> "$pcrf"
+	if [ "$CONFIG_USB_KEYBOARD" = "y" -o -r /lib/modules/libata.ko -o -x /bin/hotp_verification ]; then
+		# Here, we take pcr 5 into consideration if modules are expected to be measured+loaded
+		# 
+		# binary pcr dump can only go via stderr for redirection
+		# sadly this busybox has buggy support for "2>>" and "2|"
+		# so we need workaround...
+		tpm2 pcrread -o /dev/stderr sha256:5 2>&1 >/dev/console | cat >> "$pcrf"
+	else
+		#no kernel modules are expected to be measured+loaded
+		dd if=/dev/zero bs=32 count=1 >> "$pcrf"
+	fi
+	# Use pcr 23 to precompute the value for pcr 6
+	tpmr extend -ix 23 -if /tmp/luksDump.txt
+	tpm2 pcrread -o /dev/stderr sha256:23 2>&1 >/dev/console | cat >> "$pcrf"
+	#TODO: delete the following pcrs output on screen
+	# goal is to validate that what is in pcr 23 is at pcr 6 at unseal
+	pcrs
+	tpm2 pcrreset 23
+	# We take into consideration user files in cbfs
+	tpm2 pcrread -o /dev/stderr sha256:7 2>&1 >/dev/console | cat >> "$pcrf"
+	if [ "$CONFIG_AUTO_UNLOCK" = "y" ]; then
+		#TODO: There is no CONFIG_AUTO_UNLOCK. Should be removed
+		tpmr seal "$KEY_FILE" "0x8100000$TPM_INDEX" sha256:0,1,2,3,4,5,6,7 "$pcrf"
+	else
+		#TODO: wrap TPM disk encryption key passphrase, otherwise prompt to user looks like if we were asking for TPM ownership passphrase
+		#TODO: everything is supposed to be under $pcrf, why considering them twice?
+		# TODO: review syntax to not duplicate expending pcr 2 times with pcr0-7: find a way to only use $pcrf? : sha256 "$pcrf" "$key_password"
+		tpmr seal "$KEY_FILE" "0x8100000$TPM_INDEX" sha256:0,1,2,3,4,5,6,7 "$pcrf" "$key_password"
+	fi
+	if [ $? -eq 0 ]; then
+		# should be okay if this fails
+		shred -n 10 -z -u "$pcrf".* 2> /dev/null || true
+	fi
 fi
 
 shred -n 10 -z -u "$TPM_SEALED" 2> /dev/null \
 || warn "Failed to delete the sealed secret - continuing"
+
+cp /tmp/luksDump.txt "$paramsdir/kexec_lukshdr_hash.txt" \
+|| warn "Failed to have hashes of LUKS header - continuing"
diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -50,6 +50,22 @@ bootdir="${bootdir%%/}"
 paramsdev="${paramsdev%%/}"
 paramsdir="${paramsdir%%/}"
 
+PRIMHASH_FILE="$paramsdir/kexec_primhdl_hash.txt"
+if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	if [ -r "$PRIMHASH_FILE" ]; then
+		sha256sum -c "$PRIMHASH_FILE" \
+			|| {
+			echo "FATAL: Hash of TPM2 primary key handle mismatch!";
+			echo "If you have not intentionally regenerated TPM2 primary key,";
+			warn "your system may have been compromised!";
+		}
+	else
+		echo "WARNING: Hash of TPM2 primary key handle does not exist!"
+		echo "Please rebuild the boot hash tree."
+		default_failed="y"
+	fi
+fi
+
 verify_global_hashes()
 {
 	echo "+++ Checking verified boot hash file "
@@ -299,23 +315,22 @@ do_boot()
 		die "!!! Missing required boot hashes"
 	fi
 
-	if [ "$CONFIG_TPM" = "y" \
-		-a -r "$TMP_KEY_DEVICES" ]; then
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] && [ -r "$TMP_KEY_DEVICES" ]; then
 		INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
-		|| die "!!! Failed to extract the initrd from boot option"
+			|| die "!!! Failed to extract the initrd from boot option"
 		if [ -z "$INITRD" ]; then
 			die "!!! No initrd file found in boot option"
 		fi
 
 		kexec-insert-key $INITRD \
-		|| die "!!! Failed to insert disk key into a new initrd"
+			|| die "!!! Failed to insert disk key into a new initrd"
 
 		kexec-boot -b "$bootdir" -e "$option" \
 			-a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
-		|| die "!!! Failed to boot w/ options: $option"
+			|| die "!!! Failed to boot w/ options: $option"
 	else
 		kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
-		|| die "!!! Failed to boot w/ options: $option"
+			|| die "!!! Failed to boot w/ options: $option"
 	fi
 }
 
@@ -344,11 +359,12 @@ while true; do
 		user_select
 	fi
 
-	if [ "$CONFIG_TPM" = "y" \
-		-a ! -r "$TMP_KEY_DEVICES" ]; then
-		# Extend PCR4 as soon as possible
-		tpm extend -ix 4 -ic generic \
-		|| die "Failed to extend PCR 4"
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		if [ ! -r "$TMP_KEY_DEVICES" ]; then
+			# Extend PCR4 as soon as possible
+			tpmr extend -ix 4 -ic generic \
+				|| die "Failed to extend PCR 4"
+		fi
 	fi
 
 	# if no saved options, scan the boot directory and generate
@@ -356,7 +372,7 @@ while true; do
 		scan_options
 	fi
 
-	if [ "$CONFIG_TPM" = "y" ]; then
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
 		# Optionally enforce device file hashes
 		if [ -r "$TMP_HASH_FILE" ]; then
 			valid_global_hash="n"
@@ -368,7 +384,7 @@ while true; do
 			fi
 		fi
 
-		if [ -r "$TMP_ROLLBACK_FILE" ]; then
+		if [ "$CONFIG_IGNORE_ROLLBACK" != "y" -a -r "$TMP_ROLLBACK_FILE" ]; then
 			# in the case of iso boot with a rollback file, do not assume valid
 			valid_rollback="n"
 
