Added TPM secret management to generic boot
Also cleaned up error handling and boot parsing edge cases

diff --git a/initrd/bin/kexec-boot b/initrd/bin/kexec-boot
--- a/initrd/bin/kexec-boot
+++ b/initrd/bin/kexec-boot
@@ -1,16 +1,28 @@
 #!/bin/sh
+# Launches kexec from saved configuration entries
+set -e -o pipefail
 . /etc/functions
 
 dryrun="n"
-while getopts "b:e:r:a:d" arg; do
+printfiles="n"
+printinitrd="n"
+while getopts "b:e:r:a:o:fi" arg; do
 	case $arg in
 		b) bootdir="$OPTARG" ;;
 		e) entry="$OPTARG" ;;
 		r) cmdremove="$OPTARG" ;;
 		a) cmdadd="$OPTARG" ;;
-		d) dryrun="y" ;;
+		o) override_initrd="$OPTARG" ;;
+		f) dryrun="y"; printfiles="y" ;;
+		i) dryrun="y"; printinitrd="y" ;;
 	esac
 done
+
+if [ -z "$bootdir" -o -z "$entry" ]; then
+	die "Usage: $0 -b /boot/ -e 'kexec params|...|...'"
+fi
+
+bootdir=${bootdir%%"/"}
 
 kexectype=`echo $entry | cut -d\| -f2`
 kexecparams=`echo $entry | cut -d\| -f3- | tr '|' '\n'`
@@ -21,11 +33,15 @@ cmdadd="intel_iommu=on $cmdadd"
 cmdremove="quiet $cmdremove"
 
 fix_file_path() {
-	if [ "$dryrun" = "y" ]; then echo ".$firstval"; fi
+	if [ "$printfiles" = "y" ]; then
+		# output file relative to local boot directory
+		echo ".$firstval"
+	fi
 
-	filepath=`find $bootdir -path "*$firstval" | tail -1`
+	filepath="$bootdir$firstval"
+
 	if ! [ -r $filepath ]; then
-		die "failed to find file $firstval"
+		die "Failed to find file $firstval"
 	fi
 }
 
@@ -41,7 +57,7 @@ adjust_cmd_line() {
 	fi
 }
 
-first_module=y
+module_number="1"
 while read line
 do
 	key=`echo $line | cut -d\  -f1`
@@ -64,14 +80,31 @@ do
 	if [ "$key" = "module" ]; then
 		fix_file_path
 		cmdline="$restval"
-		if [ -n "$first_module" ]; then
-			adjust_cmd_line
-			unset first_module
+		if [ "$kexectype" = "xen" ]; then
+			if [ "$module_number" -eq 1 ]; then
+				adjust_cmd_line
+			elif [ "$module_number" -eq 2 ]; then
+				if [ "$printinitrd" = "y" ]; then
+					# output the current path to initrd
+					echo $filepath
+				fi
+				if [ -n "$override_initrd" ]; then
+					filepath="$override_initrd"
+				fi
+			fi
 		fi
+		module_number=`expr $module_number + 1`
 		kexeccmd="$kexeccmd --module \"$filepath $cmdline\""
 	fi
 	if [ "$key" = "initrd" ]; then
 		fix_file_path
+		if [ "$printinitrd" = "y" ]; then
+			# output the current path to initrd
+			echo $filepath
+		fi
+		if [ -n "$override_initrd" ]; then
+			filepath="$override_initrd"
+		fi
 		kexeccmd="$kexeccmd --initrd=$filepath"
 	fi
 	if [ "$key" = "append" ]; then
diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -1,5 +1,6 @@
 #!/bin/sh
 # Save these options to be the persistent default
+set -e -o pipefail
 . /etc/functions
 
 while getopts "b:d:p:e:i:" arg; do
@@ -43,9 +44,11 @@ if [ ! -d $paramsdir ]; then
 	mkdir -p $paramsdir \
 	|| die "Failed to create params directory"
 fi
-rm "$paramsdir/kexec_default.*.txt" 2>/dev/null
+rm "$paramsdir/kexec_default.*.txt" 2>/dev/null || true
 echo "$entry" > $ENTRY_FILE
-cd $bootdir && kexec-boot -e "$entry" -d | xargs sha256sum > $HASH_FILE
+cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f | \
+	xargs sha256sum > $HASH_FILE \
+|| die "Failed to create hashes of boot files"
 if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
 	die "Failed to write default config"
 fi
diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -1,6 +1,6 @@
 #!/bin/sh
 # Generic configurable boot script via kexec
-set -o pipefail
+set -e -o pipefail
 . /etc/config
 . /etc/functions
 
@@ -119,7 +119,7 @@ scan_options() {
 	option_file="/tmp/kexec_options.txt"
 	if [ -r $option_file ]; then rm $option_file; fi
 	for i in `find $bootdir -name "$config"`; do
-		kexec-parse-boot $i >> $option_file
+		kexec-parse-boot "$bootdir" "$i" >> $option_file
 	done
 	if [ ! -r $option_file ]; then
 		die "Failed to parse any boot options"
@@ -222,18 +222,40 @@ do_boot()
 		return
 	fi
 
-	kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove"
-	die "!!! Failed to boot w/ options: $option"
+	if [ -r "$TMP_KEY_DEVICES" ]; then
+		INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
+		|| die "!!! Failed to extract the initrd from boot option"
+		if [ -z "$INITRD" ]; then
+			die "!!! No initrd file found in boot option"
+		fi
+
+		kexec-insert-key $INITRD \
+		|| die "!!! Failed to insert disk key into a new initrd"
+
+		kexec-boot -b "$bootdir" -e "$option" \
+			-a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
+		|| die "!!! Failed to boot w/ options: $option"
+	else
+		kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
+		|| die "!!! Failed to boot w/ options: $option"
+	fi
 }
 
 while true; do
 	check_config $paramsdir
-
+	TMP_DEFAULT_FILE=`find /tmp/kexec/kexec_default.*.txt 2>/dev/null | head -1` || true
 	TMP_MENU_FILE="/tmp/kexec/kexec_menu.txt"
 	TMP_HASH_FILE="/tmp/kexec/kexec_hashes.txt"
-	TMP_DEFAULT_FILE=`find /tmp/kexec/kexec_default.*.txt 2>/dev/null | head -1`
 	TMP_DEFAULT_HASH_FILE="/tmp/kexec/kexec_default_hashes.txt"
 	TMP_ROLLBACK_FILE="/tmp/kexec/kexec_rollback.txt"
+	TMP_KEY_DEVICES="/tmp/kexec/kexec_key_devices.txt"
+	TMP_KEY_LVM="/tmp/kexec/kexec_key_lvm.txt"
+
+	if [ ! -r "$TMP_KEY_DEVICES" ]; then
+		# Extend PCR4 as soon as possible
+		tpm extend -ix 4 -ic generic \
+		|| die "Failed to extend PCR 4"
+	fi
 
 	# if no saved options, scan the boot directory and generate
 	if [ ! -r "$TMP_MENU_FILE" ]; then
