Added rollback protection to generic boot
Changed the checking of required hashes or required rollback state
to be right before boot, allowing the user to sign/set defaults
in interactive mode.

Also cleaned up usages of recovery and fixed iso parameter
regression.

diff --git a/initrd/bin/kexec-iso-init b/initrd/bin/kexec-iso-init
--- a/initrd/bin/kexec-iso-init
+++ b/initrd/bin/kexec-iso-init
@@ -16,15 +16,18 @@ if ! [ -r "$ISOSIG" ]; then
 fi
 
 gpgv "$ISOSIG" "$MOUNTED_ISO_PATH" \
-	|| recovery 'ISO signature failed'
+	|| die 'ISO signature failed'
 
 echo '+++ Mounting ISO and booting'
 mount -t iso9660 -o loop $MOUNTED_ISO_PATH /boot \
-	|| recovery '$MOUNTED_ISO_PATH: Unable to mount /boot'
+	|| die '$MOUNTED_ISO_PATH: Unable to mount /boot'
 
 DEV_UUID=`blkid $DEV | tail -1 | tr " " "\n" | grep UUID | cut -d\" -f2`
 ADD="fromiso=/dev/disk/by-uuid/$DEV_UUID/$ISO_PATH"
 REMOVE=""
+
+paramsdir="/media/kexec_iso/$ISO_PATH/"
+check_config $paramsdir
 
 ADD_FILE=/tmp/kexec/kexec_iso_add.txt
 if [ -r $ADD_FILE ]; then
@@ -40,4 +43,7 @@ if [ -r $REMOVE_FILE ]; then
 fi
 
 # Call kexec and indicate that hashes have been verified
-kexec-select-boot -b /boot/ -d /media/ -p "/media/kexec_iso/$ISO_PATH/" -a "$ADD" -r "$REMOVE" -c "*.cfg" -u -h
+kexec-select-boot -b /boot/ -d /media/ -p "$paramsdir" \
+	-a "$ADD" -r "$REMOVE" -c "*.cfg" -u -i
+
+die "Something failed in selecting boot"
diff --git a/initrd/bin/kexec-sign-config b/initrd/bin/kexec-sign-config
--- a/initrd/bin/kexec-sign-config
+++ b/initrd/bin/kexec-sign-config
@@ -2,24 +2,57 @@
 # Sign a valid directory of kexec params
 . /etc/functions
 
-MEDIA="$1"
+rollback="n"
+update_counter="n"
+while getopts "p:c:u" arg; do
+	case $arg in
+		p) paramsdir="$OPTARG" ;;
+		c) counter="$OPTARG"; rollback="y" ;;
+		u) update_counter="y"; rollback="y" ;;
+	esac
+done
 
-if [ -z "$MEDIA" ]; then
-	die "Usage: $0 /boot "
+if [ -z "$paramsdir" ]; then
+	die "Usage: $0 -p /boot/ [ -u | -c counter ]"
 fi
 
 confirm_gpg_card
 
+if [ "$rollback" = "y" ]; then
+	rollback_file="$paramsdir/kexec_rollback.txt"
+
+	if [ -n "$counter" ]; then
+		# use existing counter
+		read_tpm_counter $counter \
+		|| die "$paramsdir: Unable to read tpm counter '$counter'"
+	else
+		# increment counter
+		check_tpm_counter $rollback_file \
+		|| die "$paramsdir: Unable to find/create tpm counter"
+		counter="$TPM_COUNTER"
+
+		increment_tpm_counter $counter \
+		|| die "$paramsdir: Unable to increment tpm counter"
+	fi
+
+	sha256sum /tmp/counter-$counter > $rollback_file \
+	|| die "$paramsdir: Unable to create rollback file"
+fi
+
+param_files=`find $paramsdir/kexec*.txt`
+if [ -z "$param_files" ]; then
+	die "$paramsdir: No kexec parameter files to sign"
+fi
+
 for tries in 1 2 3; do
-	if sha256sum `find $MEDIA/kexec*.txt` | gpg \
+	if sha256sum $param_files | gpg \
 		--digest-algo SHA256 \
 		--detach-sign \
 		-a \
-		> $MEDIA/kexec.sig \
+		> $paramsdir/kexec.sig \
 	; then
 		exit 0
 	fi
 done
 
-warn "$MEDIA: Unable to sign boot hashes"
-exit 1
+die "$paramsdir: Unable to sign kexec hashes"
diff --git a/initrd/bin/usb-scan b/initrd/bin/usb-scan
--- a/initrd/bin/usb-scan
+++ b/initrd/bin/usb-scan
@@ -7,13 +7,13 @@
 # Unmount any previous boot device
 if grep -q /boot /proc/mounts ; then
 	umount /boot \
-		|| recovery '$CONFIG_USB_BOOT_DEV: Unable to unmount /boot'
+		|| die '$CONFIG_USB_BOOT_DEV: Unable to unmount /boot'
 fi
 
 # Mount the USB boot device
 if ! grep -q /media /proc/mounts ; then
 	mount-usb "$CONFIG_USB_BOOT_DEV" \
-		|| recovery '$CONFIG_USB_BOOT_DEV: Unable to mount /media'
+		|| die '$CONFIG_USB_BOOT_DEV: Unable to mount /media'
 fi
 
 # Check for ISO first
@@ -31,7 +31,7 @@ get_menu_option() {
 		option_index
 
 	if [ "$option_index" = "a" ]; then
-		recovery "Aborting boot attempt"
+		die "Aborting boot attempt"
 	fi
 
 	if [ "$option_index" = "s" ]; then
@@ -56,7 +56,7 @@ if [ `cat /tmp/iso_menu.txt | wc -l` -gt 0 ]; then
 		ISO=${option:7} # remove /media/ to get device relative path
 		kexec-iso-init $MOUNTED_ISO $ISO $CONFIG_USB_BOOT_DEV
 
-		recovery "Something failed..."
+		die "Something failed in iso init"
 	fi
 fi
 
@@ -64,4 +64,4 @@ echo "!!! Could not find any ISO, trying bootable USB"
 # Attempt to pull verified config from device
 kexec-select-boot -b /media/ -c "*.cfg" -u
 
-recovery "Something failed..."
+die "Something failed in selecting boot"
