kexec-save-default: Always update TPM2 primary object handle hash
Resetting the TPM creates a new primary object, and there is no reason
for kexec-save-default to sign an old hash.  Always update the hash
instead of creating it only if it doesn't exist.

Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -125,10 +125,8 @@ if [ ! -d $paramsdir ]; then
 fi
 
 if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
-	if [ ! -r "$PRIMHASH_FILE" ]; then
-		sha256sum /tmp/primary.handle > "$PRIMHASH_FILE" \
-			|| die "ERROR: Failed to Hash TPM2 primary key handle!"
-	fi
+	sha256sum /tmp/primary.handle > "$PRIMHASH_FILE" \
+		|| die "ERROR: Failed to Hash TPM2 primary key handle!"
 fi
 
 rm $paramsdir/kexec_default.*.txt 2>/dev/null || true
