initrd: use tpmx extend wrapper
Board specific scripts (ie t430-flash) have not been modified.

Signed-off-by: Cody Ho <codyho@stanford.edu>

diff --git a/initrd/bin/kexec-insert-key b/initrd/bin/kexec-insert-key
--- a/initrd/bin/kexec-insert-key
+++ b/initrd/bin/kexec-insert-key
@@ -46,8 +46,7 @@ if ! kexec-unseal-key "$INITRD_DIR/secret.key" ; then
 fi
 
 # Override PCR 4 so that user can't read the key
-tpm extend -ix 4 -ic generic \
-	|| die 'Unable to scramble PCR'
+tpmx extend generic || die 'Unable to scramble PCR'
 
 # Check to continue
 if [ "$unseal_failed" = "y" ]; then
diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -338,12 +338,8 @@ while true; do
 		user_select
 	fi
 
-	if [ "$CONFIG_TPM" = "y" \
-		-a ! -r "$TMP_KEY_DEVICES" ]; then
-		# Extend PCR4 as soon as possible
-		tpm extend -ix 4 -ic generic \
-		|| die "Failed to extend PCR 4"
-	fi
+	# Extend PCR4 as soon as possible
+	tpmx extend generic || die "Failed to extend PCR 4"
 
 	# if no saved options, scan the boot directory and generate
 	if [ ! -r "$TMP_MENU_FILE" ]; then
