load the xhci USB3 modules as well

diff --git a/initrd/bin/mount-usb b/initrd/bin/mount-usb
--- a/initrd/bin/mount-usb
+++ b/initrd/bin/mount-usb
@@ -10,6 +10,15 @@ if ! lsmod | grep -q ehci_pci; then
 	insmod /lib/modules/ehci-pci.ko \
 	|| die "ehci_pci: module load failed"
 fi
+if ! lsmod | grep -q xhci_hcd; then
+	insmod /lib/modules/xhci-hcd.ko \
+	|| die "ehci_hcd: module load failed"
+fi
+if ! lsmod | grep -q xhci_pci; then
+	insmod /lib/modules/xhci-pci.ko \
+	|| die "ehci_pci: module load failed"
+	sleep 5
+fi
 
 if [ ! -d /media ]; then
 	mkdir /media
