oem-provisioning attended one-shot filling of required information
initrd/bin:
factory-reset-nitrokey-libremkey.sh: cosmetic whiptail changes
gui-init: Cosmetic changes and added TODOs.
kexec-save-default: added TODOs
mount-sdcard: added logic to properly bypass PCR5 mods when in OEM so we can add Disk Unlock Key. Added TODOs
reencrypt-luks: Added logic to confirm to the user the presence of a bad sdcard. TODO: make it dynamic.

initrd/etc/functions:
- removed enable-sdcard, put it in mount-sdcard to mitigate PCR5 modification. See above.
- added notify to show selected passphrases on screen
- Cosmetic correction to Whiptail menu
- Changed hardcoded EFF diceware sampling to 800 words on screen when manual mode is selected for passphrase gen.

modules:
cryptsetup: version bumped to 1.7.5 (latest)
libgcrypt: GPG2 and cryptsetup dependency. version bumped to 1.8.4 (latest)

patches/cryptsetup-1.7.5.patch: Copy of 1.7.3 as is

Functional TODO:
- kexec-save-default prompts to choose between /dev/mmcp0p2 and /dev/sda2.... Shortest fix would be to reuse /boot/kexec_key_devices.txt which points to /dev/sda2 per OEM prior setting of Disk Unlock Key.

diff --git a/initrd/bin/mount-sdcard b/initrd/bin/mount-sdcard
--- a/initrd/bin/mount-sdcard
+++ b/initrd/bin/mount-sdcard
@@ -2,41 +2,110 @@
 # Mount a SDCARD device
 . /etc/functions
 
+enable_sdcard()
+{
+  #OEM ReOwnership Wizard, when attempting to load /media/oem-provisioning,
+  #requires mmc and sdhci kernel modules to be inserted here, which would 
+  #normally modify PCR 5 by calling the /sbin/insmod wrapper, which 
+  #measures the modules prior to loading them.
+  #
+  #We bypass those measurements here by calling busybox's insmod directly,
+  #keeping PCR5 intact so that calling kexec-seal-key (to add Disk Unlock Key)
+  #in OEM mode gives the same measurements then when calling kexec-unseal-key
+  #in normal boot mode after OEM reownership, making the release of the Disk
+  #Unlock Key consistent.
+  mount_boot
+  if [ -e /boot/oem ]; then
+    warn "Loading card reader (sdcard) related modules..."
+    #TODO: understand why conditional aliases don't work. It works on mount-usb :|
+    #alias insmod='busybox insmod'
+    #debug "Testing insmod in enable_sdcard just after alias: $(insmod)"
+    #even last debug happens after PCR5 being modified.... Changing tactic. Duplicating logic.
+    if [ "$CONFIG_LINUX_SDHCI" = "y" ]; then
+      if ! lsmod | grep -q mmc_core; then
+        busybox insmod /lib/modules/mmc_core.ko \
+        || die "mmc_core: module load failed"
+      fi
+      if ! lsmod | grep -q mmc_block; then
+        busybox insmod /lib/modules/mmc_block.ko \
+        || die "mmc_block: module load failed"
+      fi
+      if ! lsmod | grep -q sdhci; then
+        busybox insmod /lib/modules/sdhci.ko \
+        || die "sdhci: module load failed"
+      fi
+      if ! lsmod | grep -q sdhci_pci; then
+        busybox insmod /lib/modules/sdhci-pci.ko \
+        || die "sdhci-pci: module load failed"
+      fi
+    fi
+  else
+    #TODO: For some reason, the alias is not kept outside of the if so we replicate here with insmod which measures modules
+    if [ "$CONFIG_LINUX_SDHCI" = "y" ]; then
+      if ! lsmod | grep -q mmc_core; then
+        insmod /lib/modules/mmc_core.ko \
+        || die "mmc_core: module load failed"
+      fi
+      if ! lsmod | grep -q mmc_block; then
+        insmod /lib/modules/mmc_block.ko \
+        || die "mmc_block: module load failed"
+      fi
+      if ! lsmod | grep -q sdhci; then
+        insmod /lib/modules/sdhci.ko \
+        || die "sdhci: module load failed"
+      fi
+      if ! lsmod | grep -q sdhci_pci; then
+        insmod /lib/modules/sdhci-pci.ko \
+        || die "sdhci-pci: module load failed"
+      fi
+    fi
+  fi
+}
+
 is_Luks_luksOpen()
 {
   cryptsetup isLuks $SDCARD_MOUNT_DEVICE
   if [ $(echo $?) == 0 ]; then
-    echo -e "\n\nSDCARD Device $SDCARD_MOUNT_DEVICE is encrypted.\nPlease type $oem_name provided Disk Recovery Key passphrase at next prompt.\n"
+    echo -e "\n\nSDCARD Device $SDCARD_MOUNT_DEVICE is encrypted.\n"
+    
+    if [ -e /boot/oem ]; then
+      if ! grep -q luks_reencrypted /boot/oem ; then
+        echo -e "Please type provided $oem_name actual Disk Recovery Key passphrase at next prompt.\n"
+      else
+        echo -e "Please type your chosen new Disk Recovery Key passphrase at next prompt.\n"
+      fi
+    fi
+
     cryptsetup luksOpen $SDCARD_MOUNT_DEVICE sdcarddev
-    if [ $(echo $?) == 0 ] && [ $(grep -q oem_provisioning_partition /boot/oem) ]; then
-        mount -o remount,rw /boot
-        echo "oem_provisioning_partition=$SDCARD_MOUNT_DEVICE" >> /boot/oem
-        mount -o remount,ro /boot
+    if [ $(echo $?) == 0 ]; then
+      mount_boot
+      if [ -e /boot/oem ]; then
+        if ! grep -q ^oem_provisioning_partition /boot/oem ; then
+          mount -o remount,rw /boot
+          echo "oem_provisioning_partition=$SDCARD_MOUNT_DEVICE" >> /boot/oem
+          mount -o remount,ro /boot
+        fi
+      fi
     fi
     SDCARD_MOUNT_DEVICE="/dev/mapper/sdcarddev"
   else
     clear
-    notify "OEM Reownership Wizard only supports provisioning to/from a LUKS encrypted partition. Please prepare such sdcard and try again. System will now power off."
-    poweroff
+    if [ -e /boot/oem ]; then
+      notify "OEM Reownership Wizard only supports auto-provisioning to/from a LUKS encrypted partition. Provisioning fallsback into manual mode. System will now power reboot."
+      mount -o remount,rw /boot
+      echo "no_automatic_provisioning" >> /boot/oem
+      mount -o remount,ro /boot
+      reboot
+    fi
   fi
-
 }
 
-#OEM reownership, when attempting to load /media/oem-provisioning, 
-#requires mmc and sdhci related module to be inserted through enable_sdcard.
-#which would normally modify PCR 5 through /sbin/insmod script.
-#
-#We bypass those measurements here by calling busybox's insmod directly, 
-#keeping PCR5 intact so that calling kexec-seal-key (to add Disk Unlock Key) 
-#in OEM mode gives the same measurements then when calling kexec-unseal-key 
-#in normal boot mode after OEM reownership.
 if [ -e /boot/oem ]; then
-  alias insmod='busybox insmod'
   SDCARD_MOUNT_DEVICE=$(grep "^oem_provisioning_partition=" /boot/oem | cut -d "=" -f2)
 fi
 
 enable_sdcard
-sleep 1
+sleep 1 
 
 if [ ! -d /media ]; then
   mkdir /media
@@ -54,7 +123,6 @@ if ! grep -q /media /proc/mounts ; then
         echo "+++ SDCARD Missing! Insert your SDCARD in memory card slot and press Enter to continue."
         read
       fi
-      sleep 1
       stat -c %N /sys/block/mmc* | grep mmc | cut -f1 -d ' ' | sed "s/[']//g;s|/sys/block|/dev|" > /tmp/sdcard_block_devices
       if [ -z `cat /tmp/sdcard_block_devices` ]; then
         if [ -x /bin/whiptail ]; then
diff --git a/initrd/bin/reencrypt-luks b/initrd/bin/reencrypt-luks
--- a/initrd/bin/reencrypt-luks
+++ b/initrd/bin/reencrypt-luks
@@ -38,7 +38,7 @@ select_luks_container()
 }
 
 if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_reencryption" ]; then
-  #if no USB oem-privisioning file provides actual Disk Recovery Key
+  #if no oem-privisioning file provides actual Disk Recovery Key
   if [ -z "$oem_luks_actual_Disk_Recovery_Key" ]; then
     whiptail --title 'Reencrypt actual LUKS container with a new user selected strong passphrase?' \
       --msgbox "This will replace the actual Disk Recovery Key.\n\nThe passphrase associated with this key will be asked to the user in the\n following conditions:\n1-Every boot if no Disk unlock key was added to the TPM\n2-If the TPM fails (Hardware failure)\n3-If the firmware has been tampered with/upgraded/modified by the user\n\nThis process requires you to type the actual Disk Recovery Key passphrase\nand will delete the actual Disk unlock key released by the TPM into\nLUKS (slot 1) if present.\n\nAt the next prompt, you may be asked to select which file corresponds to\nthe LUKS device container. Normally, it should be /dev/sda2.\n\nHit Enter to continue." 30 90
@@ -50,6 +50,7 @@ if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_reencryption" ]
     #USB "oem-privisioning" file provides actual Disk Recovery Key
     echo -n "$oem_luks_actual_Disk_Recovery_Key" > /tmp/oem_luks_actual_Disk_Recovery_Key
     select_luks_container
+    warn "Reencrypting "$LUKS" LUKS encrypted drive content with actual Recovery Disk Key passphrase..."
     cryptsetup-reencrypt -B 32 --use-directio "$LUKS" --key-slot 0 --key-file /tmp/oem_luks_actual_Disk_Recovery_Key
   fi
   
@@ -64,6 +65,29 @@ if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_reencryption" ]
   else
   #Successfully reencrypted LUKS container with current Disk Recovery Key passphrase. Write successful state in oem file
     if [ -e /boot/oem ];then
+      #Reencrypting OEM provided sdcard
+      SDCARD_MOUNT_DEVICE=$(grep "^oem_provisioning_partition=" /boot/oem | cut -d "=" -f2)
+      if [ -n "$SDCARD_MOUNT_DEVICE" ]; then
+        umount /media 2> /dev/null         
+        cryptsetup luksClose /dev/mapper/sdcarddev 2> /dev/null 
+        warn "Reencrypting $SDCARD_MOUNT_DEVICE LUKS encrypted drive content with actual LUKS Recovery Disk Key passphrase..."
+        cryptsetup-reencrypt "$SDCARD_MOUNT_DEVICE" --key-slot 0 --key-file /tmp/oem_luks_actual_Disk_Recovery_Key
+      fi
+      if [ $(echo $?) -ne 0 ]; then
+        #TODO: Would be awesome to thread a watcher that would check in kernel output for sector errors and kill cryptsetup-reencrypt.
+        #Otherwise, reencrypting sdcard can take forever, and the result is corrupted LUKS container anyway....
+        #For the moment, we catch it only when it fails.
+        warn "An error occured when reencrypting $SDCARD_MOUNT_DEVICE device. Probably sector corruption of unreliable sdcard flash..."
+        error "Outputing kernel log when ready:"
+        dmesg
+        warn "Unfortunately, the one-shot provisioning of OEM Reownership won't be able to provide automatic storing/fetching of credentials."
+        mount -o remount,rw /boot
+        echo "no_automatic_provisioning" >> /boot/oem
+        mount -o remount,ro /boot
+        warn "The OEM Reownership Wizard is now set to be fed manually by the user at each steps, without backup. Take notes of your secrets!" 
+        error "Rebooting"
+        reboot
+      fi
       mount -o remount,rw /boot
       echo "luks_reencrypted" >> /boot/oem
       reownership_state="luks_password_change"
@@ -75,17 +99,18 @@ if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_reencryption" ]
 fi
 
 if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_password_change" ]; then
-  #if actual or new Disk Recovery Key is not provisioned by USB oem-provisioning file
+  #if actual or new Disk Recovery Key is not provisioned by oem-provisioning file
   if [ -z "$oem_luks_actual_Disk_Recovery_Key" ] || [ -z "$oem_luks_new_Disk_Recovery_Key" ] ; then
     whiptail --title 'Changing LUKS Disk Recovery Key passphrase' --msgbox \
       "Please enter current Disk Recovery Key passphrase (slot 0).\nThen choose a strong passphrase of your own.\n\n**DICEWARE passphrase methodology is STRONGLY ADVISED.**\n\nHit Enter to continue" 30 60
     select_luks_container
     cryptsetup luksChangeKey "$LUKS" --key-slot 0 --tries 3
   else
-    #if actual and new Disk Recovery Key is provisioned by USB oem-provisioning file
+    #if actual and new Disk Recovery Key is provisioned by oem-provisioning file
     select_luks_container
     echo -n "$oem_luks_new_Disk_Recovery_Key" > /tmp/oem_luks_new_Disk_Recovery_Key
     echo -n "$oem_luks_actual_Disk_Recovery_Key" > /tmp/oem_luks_actual_Disk_Recovery_Key
+    warn "Changing "$LUKS" LUKS encrypted disk passphrase to new Disk Recovery Key passphrase..."
     cryptsetup luksChangeKey "$LUKS" --key-slot 0 --key-file=/tmp/oem_luks_actual_Disk_Recovery_Key /tmp/oem_luks_new_Disk_Recovery_Key
   fi
   #Validate past cryptsetup attempts
@@ -93,19 +118,28 @@ if [ -n "$reownership_state" ] && [ "$reownership_state" = "luks_password_change
     #Cryptsetup was unsuccessful
     whiptail --title 'Invalid LUKS passphrase?' --msgbox \
       "The LUKS Disk Recovery Key passphrase was provided to you by the OEM over\n secure communication channel.\n\nIf you previously changed it and do not remember it,\n you will have to reinstall OS from a USB drive.\nTo do so, put OS ISO file and it's signature file on root of USB drive,\n And select Boot from USB\n\nHit Enter to continue." 30 60
-    shred -n 10 -z -u /tmp/oem_luks_new_Disk_Recovery_Key 2> /dev/null
-    shred -n 10 -z -u /tmp/oem_luks_actual_Disk_Recovery_Key 2> /dev/null
   else
     #Cryptsetup was successful
-    if [ -e /boot/oem ];then
+    if [ -e /boot/oem ]; then
+      SDCARD_MOUNT_DEVICE=$(grep "^oem_provisioning_partition=" /boot/oem | cut -d "=" -f2)
+      if [ -n "$SDCARD_MOUNT_DEVICE" ]; then
+        umount /media 2> /dev/null 
+        cryptsetup luksClose /dev/mapper/sdcarddev 2> /dev/null 
+        warn "Changing $SDCARD_MOUNT_DEVICE LUKS encrypted disk passphrase to new Recovery Disk Key passphrase..."
+        cryptsetup luksChangeKey "$SDCARD_MOUNT_DEVICE" --key-slot 0 --key-file=/tmp/oem_luks_actual_Disk_Recovery_Key /tmp/oem_luks_new_Disk_Recovery_Key
+      fi
       mount -o remount,rw /boot
       echo "luks_passwd_changed" >> /boot/oem
       mount -o remount,ro /boot
-      shred -n 10 -z -u /tmp/oem_luks_new_Disk_Recovery_Key 2> /dev/null
-      shred -n 10 -z -u /tmp/oem_luks_actual_Disk_Recovery_Key 2> /dev/null
-      unset oem_luks_actual_Disk_Recovery_Key
-      unset oem_luks_new_Disk_Recovery_Key
     fi
   fi
+  #Cleanup
+  shred -n 10 -z -u /tmp/oem_luks_new_Disk_Recovery_Key 2> /dev/null
+  shred -n 10 -z -u /tmp/oem_luks_actual_Disk_Recovery_Key 2> /dev/null
+  unset oem_luks_actual_Disk_Recovery_Key
+  unset oem_luks_new_Disk_Recovery_Key
+  notify "Your new Disk Recovery Key is now effective. The system will now reboot."
+  #TODO: Shall we set marker to set disk unlock key here?
+  reboot
   continue
 fi
