Rework /init and qubes setup scripts (issue #27, #155, #32, #29, #110)
This adds support for seamless booting of Qubes with a TPM disk key,
as well as signing of qubes files in /boot with a Yubikey.

The signed hashes also includes a TPM counter, which is incremented
when new hashes are signed.  This prevents rollback attacks against
the /boot filesystem.

The TPMTOTP value is presented to the user at the time of entering
the disk encryption keys.  Hitting enter will generate a new code.

The LUKS headers are included in the TPM sealing of the disk
encryption keys.

diff --git a/initrd/bin/qubes-init b/initrd/bin/qubes-init
--- a/initrd/bin/qubes-init
+++ b/initrd/bin/qubes-init
@@ -5,85 +5,79 @@
 # which is only set if the top level /init script has started
 # without user intervention or dropping into a recovery shell.
 
-recovery() {
-	echo >&2 "!!!!! $@"
-	rm -f /tmp/secret.key
-	tpm extend -ix 4 -ic recovery
+. /etc/functions
+. /etc/config
 
-	echo >&2 "!!!!! Starting recovery shell"
-	exec /bin/ash
-}
-
-. /config
-
-# TODO: Allow /boot to be encrypted?
-# This would require a different TPM key or a user
-# passphrase to decrypt it.
-mount -o ro "$CONFIG_QUBES_BOOT_DEV" /boot \
-	|| recovery '$CONFIG_BOOT_DEV: Unable to mount /boot'
-
-BOOT_SCRIPT=/boot/boot.sh
-if [ ! -x /boot/boot.sh ]; then
-	recovery "$BOOT_SCRIPT does not exist"
+if [ "$1" = "recovery" ]; then
+	warn "Recovery mode boot; ignoring key failures"
+	RECOVERY=1
 fi
 
-# Hand control over to the user boot script
-echo "+++ Checking $BOOT_SCRIPT"
-gpgv "$BOOT_SCRIPT.asc" "$BOOT_SCRIPT" \
-	|| recovery 'boot script signature failed'
+# TODO: Allow /boot to be encrypted?
+# This would require a different TPM key, a user passphrase to decrypt it,
+# or loading the USB modules to talk to a Yubikey to get the thing.
+if ! grep -q /boot /proc/mounts ; then
+	mount -o ro "$CONFIG_QUBES_BOOT_DEV" /boot \
+		|| recovery '$CONFIG_BOOT_DEV: Unable to mount /boot'
+fi
 
-exec "$BOOT_SCRIPT"
+BOOT_HASHES=/boot/boot.hashes
+if [ ! -r "$BOOT_HASHES" ]; then
+	recovery "$BOOT_HASHES does not exist; re-run qubes-update"
+fi
 
-recovery 'Boot script exec failed?'
+# Verify the signature on the hashes
+gpgv "$BOOT_HASHES.asc" "$BOOT_HASHES" \
+	|| recovery 'boot hashes signature failed'
 
-############################
-# For historical reference
+# Retrieve the TPM counter ID and generate its current value
+TPM_COUNTER=`grep counter $BOOT_HASHES | cut -d- -f2`
+if [ -z "$TPM_COUNTER" ]; then
+	recovery "$BOOT_HASHES: TPM counter not found?"
+fi
 
-# TODO: Allow these to be specified on the /boot device
-XEN=/boot/xen-4.6.3.heads
-INITRD=/boot/initramfs-4.4.31-11.pvops.qubes.x86_64.img
-KERNEL=/boot/vmlinuz-4.4.31-11.pvops.qubes.x86_64
+tpm counter_read -ix "$TPM_COUNTER" | tee "/tmp/counter-$TPM_COUNTER"
 
-echo "+++ Checking $XEN"
-gpgv "${XEN}.asc" "${XEN}" \
-	|| recovery 'Xen signature failed'
+# Check the hashes of all the files
+sha256sum -c "$BOOT_HASHES" \
+|| recovery "$BOOT_HASHES: hash mismatch"
 
-echo "+++ Checking $INITRD"
-gpgv "${INITRD}.asc" "${INITRD}" \
-	|| recovery 'Initrd signature failed'
+XEN=`grep /boot/xen $BOOT_HASHES | cut -d\  -f3 | tail -1`
+KERNEL=`grep /boot/vmlin $BOOT_HASHES | cut -d\  -f3 | tail -1`
+INITRD=`grep /boot/initram $BOOT_HASHES | cut -d\  -f3 | tail -1`
 
-echo "+++ Checking $KERNEL"
-gpgv "${KERNEL}.asc" "${KERNEL}" \
-	|| recovery 'Kernel signature failed'
+# Activate the dom0 group
+lvm vgchange -a y "$CONFIG_QUBES_VG" \
+	|| recovery "$CONFIG_QUBES_VG: LVM volume group activate failed"
 
 # Measure the LUKS headers before we unseal the disk key
-/bin/qubes-measure-luks $CONFIG_QUBES_DEVS \
+qubes-measure-luks /dev/$CONFIG_QUBES_VG/* \
 	|| recovery "LUKS measure failed"
+
+# Unpack the initrd and fixup the /etc/crypttab
+# this is a hack to split it into two parts since
+# we know that the first 0x3400 bytes are the microcode
+INITRD_DIR=/tmp/secret/initrd
+SECRET_CPIO=/tmp/secret/initrd.cpio
+mkdir -p "$INITRD_DIR/etc"
 
 # Attempt to unseal the disk key from the TPM
 # should we give this some number of tries?
-unseal-key \
-	|| recovery 'Unseal disk key failed. Starting recovery shell'
+if ! unseal-key "$INITRD_DIR/secret.key" ; then
+	warn 'Unseal disk key failed'
+	if [ -z "$RECOVERY" ]; then
+		recovery 'Starting recovery shell'
+	fi
+fi
 
-# command line arguments are in the hash, so they are "correct".
-kexec \
-	-l \
-	--module "${KERNEL} root=LABEL=root ro rd.qubes.hide_all_usb rhgb" \
-	--module "${INITRD}" \
-	--command-line "no-real-mode reboot=no"
-	"${XEN}" \
-|| recovery "kexec load failed"
-
-
-kexec -l \
-	--module "${KERNEL} root=UUID=257b593f-d4ae-46ee-b499-14bc9ffd37d4 ro rd.qubes.hide_all_usb" \
-	--module "/boot/initramfs-4.4.31-11.pvops.qubes.x86_64.img" \
-	--command-line "no-real-mode reboot=no" \
-	/boot/xen-4.6.3.heads
-
-# Last step is to override PCR 6 so that user can't read the key
+# Override PCR 4 so that user can't read the key
 tpm extend -ix 4 -ic qubes \
 	|| recovery 'Unable to scramble PCR'
 
-echo "+++ Starting Qubes..."
-exec kexec -e
+echo '+++ Building initrd'
+( cd "$INITRD_DIR" ; find . | cpio -H newc -o ) > "$SECRET_CPIO"
+cat "$INITRD" >> "$SECRET_CPIO"
+
+/bin/qubes-boot "$XEN" "$KERNEL" "$SECRET_CPIO"
+
+recovery "Something failed..."
diff --git a/initrd/bin/unseal-key b/initrd/bin/unseal-key
--- a/initrd/bin/unseal-key
+++ b/initrd/bin/unseal-key
@@ -1,34 +1,48 @@
 #!/bin/sh
 # This will unseal and unecncrypt the drive encryption key from the TPM
+# The TOTP secret will be shown to the user on each encryption attempt.
 # It will then need to be bundled into initrd that is booted with Qubes.
 
 TPM_INDEX=3
 TPM_SIZE=312
 
-die() { echo >&2 "$@"; exit 1; }
-warn() { echo >&2 "$@"; }
+. /etc/functions
+mkdir -p /tmp/secret
 
+sealed_file="/tmp/secret/sealed.key"
 key_file="$1"
-if [ -z "$key_file" ]; then
-	key_file=/tmp/secret.key
-fi
 
-read -s -p "Disk encryption password: " tpm_password
-echo
+if [ -z "$key_file" ]; then
+	key_file="/tmp/secret/secret.key"
+fi
 
 tpm nv_readvalue \
 	-in "$TPM_INDEX" \
 	-sz "$TPM_SIZE" \
-	-of /tmp/sealed \
+	-of "$sealed_file" \
 || die "Unable to read key from TPM NVRAM"
 
-tpm unsealfile \
-	-if /tmp/sealed \
-	-of "$key_file" \
-	-pwdd "$tpm_password" \
-	-hk 40000000 \
-|| die "Unable to unseal disk encryption key"
+for tries in 1 2 3; do
+	tpm_password=
+	while [ -z "$tpm_password" ]; do
+		unseal-totp || die "TOTP code generation failed"
 
-rm -f /tmp/sealed
+		read -s -p "Disk unlock password: " tpm_password
+		echo
+	done
 
-exit 0
+	if tpm unsealfile \
+		-if "$sealed_file" \
+		-of "$key_file" \
+		-pwdd "$tpm_password" \
+		-hk 40000000 \
+	; then
+		rm -f /tmp/secret/sealed
+		exit 0
+	fi
+
+	pcrs
+	warn "Unable to unseal disk encryption key"
+done
+
+die "Retry count exceeded..."
