initrd/bin/flash.sh: Remove '-s' "SHA-256" mode
flash.sh had a special mode to read (like -r) and then sha256sum the
resulting file.  This is no different from just a read followed by a
sha256sum, and the only caller also had logic to sha256sum a cached
file anyway.

Just use flash.sh -r and sha256sum the result.

Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>

diff --git a/initrd/bin/seal-hotpkey b/initrd/bin/seal-hotpkey
--- a/initrd/bin/seal-hotpkey
+++ b/initrd/bin/seal-hotpkey
@@ -39,7 +39,7 @@ if [ "$CONFIG_TPM" = "y" ]; then
 		|| fatal_error "Unable to unseal HOTP secret"
 else
 	# without a TPM, use the first 20 characters of the ROM SHA256sum 
-	secret_from_rom_hash > "$HOTP_SECRET"
+	secret_from_rom_hash > "$HOTP_SECRET" || die "Reading ROM failed"
 fi
 
 # Store counter in file instead of TPM for now, as it conflicts with Heads
diff --git a/initrd/bin/unseal-hotp b/initrd/bin/unseal-hotp
--- a/initrd/bin/unseal-hotp
+++ b/initrd/bin/unseal-hotp
@@ -42,7 +42,7 @@ if [ "$CONFIG_TPM" = "y" ]; then
 	tpmr unseal 4d47 0,1,2,3,4,7 312 "$HOTP_SECRET"
 else
 	# without a TPM, use the first 20 characters of the ROM SHA256sum 
-	secret_from_rom_hash > "$HOTP_SECRET"
+	secret_from_rom_hash > "$HOTP_SECRET" || die "Reading ROM failed"
 fi
 
 if ! hotp $counter_value < "$HOTP_SECRET"; then
