LibremKey -> Librem Key

diff --git a/initrd/bin/seal-libremkey b/initrd/bin/seal-libremkey
--- a/initrd/bin/seal-libremkey
+++ b/initrd/bin/seal-libremkey
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Retrieve the sealed TOTP secret and initialize a LibremKey/NitroKey with it
+# Retrieve the sealed TOTP secret and initialize a Librem Key/NitroKey with it
 
 . /etc/functions
 
@@ -52,14 +52,14 @@ counter_value=1
 
 enable_usb
 if ! libremkey_hotp_verification info ; then
-  echo "Insert your LibremKey/NitroKey and press Enter to configure it"
+  echo "Insert your Librem Key/NitroKey and press Enter to configure it"
   read
   libremkey_hotp_verification info \
-  || die "Unable to find LibremKey/NitroKey"
+  || die "Unable to find Librem Key/NitroKey"
 fi
 
 if [ -z "$oem_gpg_Admin_PIN" ]; then
-  read -s -p "Enter your LibremKey/NitroKey Admin PIN:" admin_pin
+  read -s -p "Enter your Librem Key/NitroKey Admin PIN:" admin_pin
   echo
 else
   admin_pin=$(echo -n "$oem_gpg_Admin_PIN")
@@ -91,7 +91,7 @@ echo "$counter_value" > $HOTP_COUNTER \
 #|| die "Unable to create HOTP counter file"
 mount -o remount,ro /boot
 
-echo "LibremKey/NitroKey initialized successfully. Press Enter to continue."
+echo "Librem Key/NitroKey initialized successfully. Press Enter to continue."
 read
 
 exit 0
