unseal-hotp: fix/rename mount_boot()
Because of the way unseal-hotp is called from gui-init,
dropping to a recovery shell when failing to mount /boot
causes it to hang, leaving the user stranded until they
kill it with CTRL+C. Instead, simply return and continue
to the main GUI menu where the user can address the problem.

Rename the function to clarify difference from other versions
of mount_boot() which do drop to the recovery shell.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/bin/unseal-hotp b/initrd/bin/unseal-hotp
--- a/initrd/bin/unseal-hotp
+++ b/initrd/bin/unseal-hotp
@@ -7,12 +7,12 @@ HOTP_SEALED="/tmp/secret/hotp.sealed"
 HOTP_SECRET="/tmp/secret/hotp.key"
 HOTP_COUNTER="/boot/kexec_hotp_counter"
 
-mount_boot()
+mount_boot_or_die()
 {
   # Mount local disk if it is not already mounted
   if ! grep -q /boot /proc/mounts ; then
     mount -o ro /boot \
-      || recovery "Unable to mount /boot"
+      || die "Unable to mount /boot"
   fi
 }
 
@@ -33,7 +33,7 @@ shred -n 10 -z -u "$HOTP_SEALED" 2> /dev/null
 # Store counter in file instead of TPM for now, as it conflicts with Heads
 # config TPM counter as TPM 1.2 can only increment one counter between reboots
 # get current value of HOTP counter in TPM, create if absent
-mount_boot
+mount_boot_or_die
 
 #check_tpm_counter $HOTP_COUNTER hotp \
 #|| die "Unable to find/create TPM counter"
