libremkey_hotp_initialize: handle spaces in admin pin/pass
Fix HOTP verfication failure if LK admin pin/passphrase contains
spaces by quoting the variables when passed to functions.

Test: set LK admin pin to passphrase with spaces, generate
new TOTP/HOTP, verification passes.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

diff --git a/patches/libremkey-hotp-verification.patch b/patches/libremkey-hotp-verification.patch
--- a/patches/libremkey-hotp-verification.patch
+++ b/patches/libremkey-hotp-verification.patch
@@ -32,15 +32,18 @@
 
 --- libremkey-hotp-verification/libremkey_hotp_initialize
 +++ libremkey-hotp-verification-b/libremkey_hotp_initialize
-@@ -14,7 +14,7 @@ fi
+@@ -14,9 +14,9 @@ fi
  PIN=$1
  SECRET=$2
  COUNTER=$3
 -SECRET_B32=$(echo -n $SECRET | base32)
 +SECRET_B32=$(cat $SECRET | base32)
  
- libremkey_hotp_verification set $SECRET_B32 $PIN 
+-libremkey_hotp_verification set $SECRET_B32 $PIN 
++libremkey_hotp_verification set $SECRET_B32 "$PIN"
  if [ $? -ne 0 ]; then
+   echo "ERROR: Setting HOTP secret on Librem Key failed!"
+   exit 1
 @@ -25,7 +25,7 @@ fi
  i=9
  while [ "$i" -lt "$COUNTER" ]; do
