Make T440p scripts use Coreboot from environment
Before, the T440p blob scripts would look for Coreboot using the find
command. Now, we require the user to specify the path to Coreboot in the
COREBOOT_DIR environment variable. Also, add an output directory
argument to each script.

These changes will make it easier to integrate with the Heads build
system and CI.

diff --git a/blobs/t440p/extract b/blobs/t440p/extract
--- a/blobs/t440p/extract
+++ b/blobs/t440p/extract
@@ -4,7 +4,7 @@ set -e
 
 function usage() {
     echo -n \
-        "Usage: $(basename "$0") path_to_original_rom
+        "Usage: $(basename "$0") path_to_original_rom path_to_output_directory
 Extract Intel firmware from the original ROM.
 "
 }
@@ -13,19 +13,22 @@ if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
     if [[ "${1:-}" == "--help" ]]; then
         usage
     else
-        if [[ -n "$1" ]]; then
-            BLOB_DIR="$(cd "$(dirname "$0")" && pwd)"
-            COREBOOT_DIR="$(find "${BLOB_DIR}/../../build/x86/" -maxdepth 1 -type d -name 'coreboot-*')"
+        if [[ -z "${COREBOOT_DIR}" ]]; then
+            echo "ERROR: No COREBOOT_DIR variable defined."
+            exit 1
+        fi
 
+        if [[ -n "$1" ]]; then
             pushd "${COREBOOT_DIR}"
+
             cd util/me_cleaner
 
             # Neutralize and shrink Intel ME.
             # https://github.com/corna/me_cleaner/wiki/External-flashing#neutralize-and-shrink-intel-me-useful-only-for-coreboot
             python me_cleaner.py -S -r -t -d -O out.bin -D ifd_shrinked.bin -M me_shrinked.bin "$1"
 
-            mv ifd_shrinked.bin "${BLOB_DIR}/ifd.bin"
-            mv me_shrinked.bin "${BLOB_DIR}/me.bin"
+            mv ifd_shrinked.bin "$2/ifd.bin"
+            mv me_shrinked.bin "$2/me.bin"
             rm ./*.bin
 
             cd ../ifdtool
@@ -35,11 +38,10 @@ if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
             # original ROM.
             ./ifdtool -x "$1"
 
-            mv flashregion_3_gbe.bin "${BLOB_DIR}/gbe.bin"
+            mv flashregion_3_gbe.bin "$2/gbe.bin"
             rm ./*.bin
 
             popd
-
         else
             echo "ERROR: You must supply a path to the original ROM."
             exit 1
