flash.sh: FLASHROM_OPTIONS->FLASH_OPTIONS: require FLASH_OPTIONS to specify flash program in board configs
- boards: switch flashrom->flashprog, FLASH_OPTIONS: flashprog memory --progress --programmer internal

TODO: check, Might break:
- xx20 : x220/t420/t520: used hwseq: verify compat
- legacy : not sure --ifd bios are support: verify compat (and drop, future PR drop legacy boards anyway...)
- talos: linux_mtd is used: verify compat

Tested:
- x230 works with awesome progress bar on read, erase and write.

Signed-off-by: Thierry Laurion <insurgo@riseup.net>
Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/initrd/etc/ash_functions b/initrd/etc/ash_functions
--- a/initrd/etc/ash_functions
+++ b/initrd/etc/ash_functions
@@ -7,7 +7,7 @@ die() {
 	if [ "$CONFIG_DEBUG_OUTPUT" = "y" ];then
 		echo -e " !!! ERROR: $* !!!" | tee -a /tmp/debug.log /dev/kmsg > /dev/null;
 	else
-		echo -e "!!! ERROR: $* !!!" > &2;
+		echo -e >&2 "!!! ERROR: $* !!!";
 	fi
 	sleep 2;
 	exit 1;
@@ -17,7 +17,7 @@ warn() {
 	if [ "$CONFIG_DEBUG_OUTPUT" = "y" ];then
 		echo -e " *** WARNING: $* ***" | tee -a /tmp/debug.log /dev/kmsg > /dev/null;
 	else
-		echo -e " *** WARNING: $* ***" > &2;
+		echo -e >&2 " *** WARNING: $* ***";
 	fi
 	sleep 1;
 }
