Impose Access Restriction to the Recovery Shell
With this commit, to use recovery shell, users should authencate
themselves by connecting their OpenPGP card to the machine, in order
to prove they hold the very same secret key used to sign the boot file
list used by Heads. If they fail to pass the authencation, the machine
will exit from init and go kernel panic.

This digital signature verification routine is grafted from another
commit of mine.

This time, the feature is controlled with an exported option
"CONFIG_RECOVERY_NEED_AUTH" in board files.

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -3,11 +3,49 @@
 
 die() {
 	echo >&2 "$*";
+	# In order to die with dignity...
+	echo s > /proc/sysrq-trigger
+	echo u > /proc/sysrq-trigger
 	exit 1;
 }
 
 warn() {
 	echo >&2 "$*";
+}
+
+gpg_auth() {
+	echo >&2 "!!!!! Please authenticate with OpenPGP card to prove you own this box..."
+
+	confirm_gpg_card
+
+	# Perform a signing-based challenge-response,
+	# to authencate that the card plugged in holding
+	# the key to sign the list of boot files.
+	CR_NONCE="/tmp/secret/cr_nonce"
+	CR_SIG="/tmp/secret/cr_nonce.sig"
+
+	dd \
+		if=/dev/urandom \
+		of="$CR_NONCE" \
+		count=1 \
+		bs=20 \
+		2>/dev/null \
+		|| die "Unable to generate 20 random bytes"
+
+	for tries in 1 2 3; do
+		if gpg --digest-algo SHA256 \
+			--detach-sign \
+			-o "$CR_SIG" \
+			"$CR_NONCE" \
+			&& gpgv "$CR_SIG" "$CR_NONCE" \
+		; then
+			return 0
+		else
+			rm "$CR_SIG"
+			continue
+		fi
+	done
+	return 1
 }
 
 recovery() {
@@ -20,9 +58,14 @@ recovery() {
 	if [ "$CONFIG_TPM" = y ]; then
 		tpm extend -ix 4 -ic recovery
 	fi
-	echo >&2 "!!!!! Starting recovery shell"
-	sleep 1
-	exec /bin/ash
+
+	if [ "$CONFIG_RECOVERY_NEED_AUTH" != y ] || gpg_auth; then
+		echo >&2 "!!!!! Starting recovery shell"
+		sleep 1
+		exec /bin/ash
+	else
+		die "!!!!! Authentication failed! I am to be panic!"
+	fi
 }
 
 pause_recovery() {
