Added the ability to persist a default boot option
Similar to qubes-update, it will save then verify the hashes of
the kexec files. Once TOTP is verified, a normal boot will verify
that the file hashes and all the kexec params match and if
successful, boot directly to OS.

Also added a config option to require hash verification for
non-recovery boots, failing to recovery not met.

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -63,3 +63,28 @@ confirm_totp()
 	# clean up with a newline
 	echo
 }
+
+confirm_gpg_card()
+{
+	# setup the USB so we can reach the GPG card
+	if ! lsmod | grep -q ehci_hcd; then
+		insmod /lib/modules/ehci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
+	fi
+	if ! lsmod | grep -q ehci_pci; then
+		insmod /lib/modules/ehci-pci.ko \
+		|| die "ehci_pci: module load failed"
+	fi
+	if ! lsmod | grep -q xhci_hcd; then
+		insmod /lib/modules/xhci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
+	fi
+	if ! lsmod | grep -q xhci_pci; then
+		insmod /lib/modules/xhci-pci.ko \
+		|| die "ehci_pci: module load failed"
+		sleep 2
+	fi
+
+	gpg --card-status \
+	|| die "gpg card read failed"
+}
