Add OHCI and UHCI drivers to initrd.
USB smart card readers are most full speed devices, and there is no
"rate-matching hubs" beneath the root hub on older (e.g. GM45) plat-
forms, which has companion OHCI or UHCI controllers and needs cor-
responding drivers to communicate with card readers directly plugged
into the motherboard, otherwise a discrete USB hub should be inserted
between the motherboard and the reader.

This time I make inserting linux modules for OHCI and UHCI controllable
with option CONFIG_LINUX_USB_COMPANION_CONTROLLER.

A linux config for x200 is added as an example.

Tested on my x200s and elitebook revolve 810g1.

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -68,6 +68,41 @@ confirm_totp()
 	echo
 }
 
+enable_usb()
+{
+	if [ "$CONFIG_LINUX_USB_COMPANION_CONTROLLER" = y ]; then
+		if ! lsmod | grep -q uhci_hcd; then
+			insmod /lib/modules/uhci-hcd.ko \
+			|| die "uhci_hcd: module load failed"
+		fi
+		if ! lsmod | grep -q ohci_hcd; then
+			insmod /lib/modules/ohci-hcd.ko \
+			|| die "ohci_hcd: module load failed"
+		fi
+		if ! lsmod | grep -q ohci_pci; then
+			insmod /lib/modules/ohci-pci.ko \
+			|| die "ohci_pci: module load failed"
+		fi
+	fi
+	if ! lsmod | grep -q ehci_hcd; then
+		insmod /lib/modules/ehci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
+	fi
+	if ! lsmod | grep -q ehci_pci; then
+		insmod /lib/modules/ehci-pci.ko \
+		|| die "ehci_pci: module load failed"
+	fi
+	if ! lsmod | grep -q xhci_hcd; then
+		insmod /lib/modules/xhci-hcd.ko \
+		|| die "xhci_hcd: module load failed"
+	fi
+	if ! lsmod | grep -q xhci_pci; then
+		insmod /lib/modules/xhci-pci.ko \
+		|| die "xhci_pci: module load failed"
+		sleep 2
+	fi
+}
+
 confirm_gpg_card()
 {
 	read \
@@ -84,23 +119,7 @@ confirm_gpg_card()
 	fi
 
 	# setup the USB so we can reach the GPG card
-	if ! lsmod | grep -q ehci_hcd; then
-		insmod /lib/modules/ehci-hcd.ko \
-		|| die "ehci_hcd: module load failed"
-	fi
-	if ! lsmod | grep -q ehci_pci; then
-		insmod /lib/modules/ehci-pci.ko \
-		|| die "ehci_pci: module load failed"
-	fi
-	if ! lsmod | grep -q xhci_hcd; then
-		insmod /lib/modules/xhci-hcd.ko \
-		|| die "ehci_hcd: module load failed"
-	fi
-	if ! lsmod | grep -q xhci_pci; then
-		insmod /lib/modules/xhci-pci.ko \
-		|| die "ehci_pci: module load failed"
-		sleep 2
-	fi
+	enable_usb
 
 	gpg --card-status \
 	|| die "gpg card read failed"
