Fix tab alignment to conform with rest of script

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -181,11 +181,11 @@ check_config() {
 		return
 	fi
 
-  if [ "$2" != "force" ]; then
-    if ! sha256sum `find $1/kexec*.txt` | gpgv $1/kexec.sig - ; then
-      die 'Invalid signature on kexec boot params'
-    fi
-  fi
+	if [ "$2" != "force" ]; then
+		if ! sha256sum `find $1/kexec*.txt` | gpgv $1/kexec.sig - ; then
+			die 'Invalid signature on kexec boot params'
+		fi
+	fi
 
 	echo "+++ Found verified kexec boot params"
 	cp $1/kexec*.txt /tmp/kexec \
