usb-scan/mount: Improve USB handling
Currently, /media is mounted once per boot, which causes issues
if a user need to change USB sticks, or unknowning performs an
operation that mounts /media and then needs to access a different
USB stick later (eg, updating the firmware).

To mitigate this, always unmount /media if mounted before scanning
for USB devices, so the user can choose the correct device at the
time of its use.

Additionally, add a unique exit code for user abort so we're not
treating it the same as a failure, and use it to prevent unnecessary
GUI prompts when cancelling selection of a USB device.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

diff --git a/initrd/etc/gui_functions b/initrd/etc/gui_functions
--- a/initrd/etc/gui_functions
+++ b/initrd/etc/gui_functions
@@ -3,17 +3,20 @@
 
 mount_usb()
 {
+  # Unmount any previous USB device
+  if grep -q /media /proc/mounts ; then
+    umount /media || die "Unable to unmount /media"
+  fi
   # Mount the USB boot device
-  if ! grep -q /media /proc/mounts ; then
-    mount-usb && USB_FAILED=0 || USB_FAILED=1
+  mount-usb && USB_FAILED=0 || ( [ $? -eq 5 ] && exit 1 || USB_FAILED=1 )
+  if [ $USB_FAILED -ne 0 ]; then
+    whiptail --title 'USB Drive Missing' \
+      --msgbox "Insert your USB drive and press Enter to continue." 16 60
+    mount-usb && USB_FAILED=0 || ( [ $? -eq 5 ] && exit 1 || USB_FAILED=1 )
     if [ $USB_FAILED -ne 0 ]; then
-      whiptail --title 'USB Drive Missing' \
-        --msgbox "Insert your USB drive and press Enter to continue." 16 60
-      mount-usb && USB_FAILED=0 || USB_FAILED=1
-      if [ $USB_FAILED -ne 0 ]; then
-        whiptail $CONFIG_ERROR_BG_COLOR --title 'ERROR: Mounting /media Failed' \
-          --msgbox "Unable to mount USB device" 16 60
-      fi
+      whiptail $CONFIG_ERROR_BG_COLOR --title 'ERROR: Mounting /media Failed' \
+        --msgbox "Unable to mount USB device" 16 60
+      exit 1
     fi
   fi
 }
