xx20 boards: add xx20-hotp-maximized boards, remove hotp support from xx20-boards. Modify CircleCI conf accordingly.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -195,6 +195,30 @@ jobs:
           command: |
             ./blobs/xx20/download_parse_me.sh
       - run:
+          name: x220-hotp-maximized
+          command: |
+            rm -rf build/x220-hotp-maximized/* build/log/* && make CPUS=4 V=1 BOARD=x220-hotp-maximized || touch /tmp/failed_build
+          no_output_timeout: 3h
+      - run:
+          name: Output build failing logs
+          command: |
+            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
+      - run:
+          name: Output x220-hotp-maximized hashes
+          command: |
+            cat build/x220-hotp-maximized/hashes.txt \
+      - run:
+          name: Archiving build logs for x220-hotp-maximized
+          command: |
+            tar zcvf build/x220-hotp-maximized/logs.tar.gz ./build/log/*
+      - store-artifacts:
+          path: build/x220-hotp-maximized
+
+      - run:
+          name: Download and neuter xx20 ME (keep generated GBE and extracted IFD in tree)
+          command: |
+            ./blobs/xx20/download_parse_me.sh
+      - run:
           name: x220-maximized
           command: |
             rm -rf build/x220-maximized/* build/log/* && make CPUS=4 V=1 BOARD=x220-maximized || touch /tmp/failed_build
@@ -213,6 +237,30 @@ jobs:
             tar zcvf build/x220-maximized/logs.tar.gz ./build/log/*
       - store-artifacts:
           path: build/x220-maximized
+
+      - run:
+          name: Download and neuter xx20 ME (keep generated GBE and extracted IFD in tree)
+          command: |
+            ./blobs/xx20/download_parse_me.sh
+      - run:
+          name: t420-hotp-maximized
+          command: |
+            rm -rf build/t420-hotp-maximized/* build/log/* && make CPUS=4 V=1 BOARD=t420-hotp-maximized || touch /tmp/failed_build
+          no_output_timeout: 3h
+      - run:
+          name: Output build failing logs
+          command: |
+            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+      - run:
+          name: Output t420-hotp-maximized hashes
+          command: |
+            cat build/t420-hotp-maximized/hashes.txt \
+      - run:
+          name: Archiving build logs for t420-hotp-maximized
+          command: |
+            tar zcvf build/t420-hotp-maximized/logs.tar.gz ./build/log/*
+      - store-artifacts:
+          path: build/t420-hotp-maximized
 
       - run:
           name: Download and neuter xx20 ME (keep generated GBE and extracted IFD in tree)
