Retry CircleCI for 4.11 on Debian 10 docker - Add kgpe-d16 patch to remove HID for PCI devices (successful build on top of #1101 and #1012 per https://app.circleci.com/pipelines/github/tlaurion/heads/937/workflows/de49bea0-3f58-4a91-8891-87622f5a0eed) - CircleCI modified to build for coreboot 4.11 kgpe-d16_workstation on top of 4.15 passed workspace - CircleCI modified so that we still archive all the logs in artifacts for the current build even if failing. We now exit 1 after having archived all the log files under build/ Signed-off-by: Thierry Laurion <insurgo@riseup.net>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,6 +11,7 @@ commands:
       - run:
           name: Install dependencies
           command: |
+            ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
             apt update
             apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract sudo
       - run:
@@ -19,17 +20,17 @@ commands:
             rm -rf build/<<parameters.target>>/* build/log/* && make V=1 BOARD=<<parameters.target>> <<parameters.subcommand>> || touch ./tmpDir/failed_build
           no_output_timeout: 3h
       - run:
-          name: Output build failing logs
-          command: |
-            if [[ -f ./tmpDir/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
-      - run:
           name: Output hashes
           command: |
             cat build/<<parameters.target>>/hashes.txt || echo "No hashes for this build step..."\
       - run:
           name: Archiving build logs.
           command: |
-             tar zcvf build/<<parameters.target>>/logs.tar.gz build/log/*
+             tar zcvf build/<<parameters.target>>/logs.tar.gz $(find build/ -name "*.log")
+      - run:
+          name: Output build failing logs
+          command: |
+            if [[ -f ./tmpDir/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Step hasn't failed. Continuing with next step..."; fi \
       - store_artifacts:
           path: build/<<parameters.target>>
 
@@ -42,6 +43,7 @@ jobs:
       - run:
           name: Install dependencies
           command: |
+            ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime 
             apt update
             apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python python2 python3 wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev autoconf texinfo ncurses-dev doxygen graphviz udev libudev1 libudev-dev automake libtool rsync innoextract sudo
       - checkout
@@ -131,6 +133,7 @@ jobs:
   build:
     docker:
       - image: debian:10
+    resource_class: large
     parameters:
       target:
         type: string
@@ -146,6 +149,7 @@ jobs:
   save_cache:
     docker:
       - image: debian:10
+    resource_class: large
     steps:
       - attach_workspace:
           at: ~/
@@ -211,16 +215,18 @@ workflows:
             - x230-hotp-maximized
 
       # Coreboot 4.11
-      #- build_and_persist:
-      #    name: librem_l1um
-      #    target: librem_l1um
-      #    subcommand: ""
-      #    requires:
-      #      - x230-hotp-maximized
-
-      - save_cache:
+      - build_and_persist:
+          name: kgpe-d16_workstation
+          target: kgpe-d16_workstation
+          subcommand: ""
           requires:
             - librem_14
+
+      #Cache one workspace per Coreboot version, ideally the boards including the highest number of modules, since not rebuilt across builds.
+      #Below, 4.11, 4.13, 4.15
+      - save_cache:
+          requires:
+            - kgpe-d16_workstation
 
 #
 #
@@ -452,34 +458,33 @@ workflows:
           requires:
             - librem_14
 
-      #KGPE-D16 turned off because CircleCI built time needs to be optimized. Kernel doesn't seem to enforce MAKE_JOBS properly
-      #- build:
-      #    name: kgpe-d16_workstation-usb_keyboard
-      #    target: kgpe-d16_workstation-usb_keyboard
-      #    subcommand: ""
-      #    requires:
-      #      - librem_l1um
+      - build:
+          name: kgpe-d16_workstation-usb_keyboard
+          target: kgpe-d16_workstation-usb_keyboard
+          subcommand: ""
+          requires:
+            - kgpe-d16_workstation
 
-      #- build:
-      #    name: kgpe-d16_server
-      #    target: kgpe-d16_server
-      #    subcommand: ""
-      #    requires:
-      #      - librem_l1um
+      - build:
+          name: kgpe-d16_server
+          target: kgpe-d16_server
+          subcommand: ""
+          requires:
+            - kgpe-d16_workstation
 
-      #- build:
-      #    name: kgpe-d16_server-whiptail
-      #    target: kgpe-d16_server-whiptail
-      #    subcommand: ""
-      #    requires:
-      #      - librem_l1um
+      - build:
+          name: kgpe-d16_server-whiptail
+          target: kgpe-d16_server-whiptail
+          subcommand: ""
+          requires:
+            - kgpe-d16_workstation
 
-      #- build:
-      #    name: kgpe-d16_workstation
-      #    target: kgpe-d16_workstation
-      #    subcommand: ""
-      #    requires:
-      #      - librem_l1um
+      - build:
+          name: librem_l1um
+          target: librem_l1um
+          subcommand: ""
+          requires:
+            - kgpe-d16_workstation
 
 ########################
 ########################
