boards: rename external-flash to maximized

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -245,48 +245,48 @@ jobs:
           command: |
             ./blobs/xx20/download_parse_me.sh
       - run:
-          name: x220-external-flash
+          name: x220-maximized
           command: |
-            rm -rf build/x220-external-flash/* build/log/* && make CPUS=4 V=1 BOARD=x220-external-flash || touch /tmp/failed_build
+            rm -rf build/x220-maximized/* build/log/* && make CPUS=4 V=1 BOARD=x220-maximized || touch /tmp/failed_build
           no_output_timeout: 3h
       - run:
           name: Output build failing logs
           command: |
-            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
+            if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi \
       - run:
-          name: Output x220-external-flash hashes
+          name: Output x220-maximized hashes
           command: |
-            cat build/x220-external-flash/hashes.txt \
+            cat build/x220-maximized/hashes.txt \
       - run:
-          name: Archiving build logs for x220-external-flash
+          name: Archiving build logs for x220-maximized
           command: |
-            tar zcvf build/x220-external-flash/logs.tar.gz ./build/log/*
+            tar zcvf build/x220-maximized/logs.tar.gz ./build/log/*
       - store-artifacts:
-          path: build/x220-external-flash
+          path: build/x220-maximized
 
       - run:
           name: Download and neuter xx20 ME (keep generated GBE and extracted IFD in tree)
           command: |
             ./blobs/xx20/download_parse_me.sh
       - run:
-          name: t420-external-flash
+          name: t420-maximized
           command: |
-            rm -rf build/t420-external-flash/* build/log/* && make CPUS=4 V=1 BOARD=t420-external-flash || touch /tmp/failed_build
+            rm -rf build/t420-maximized/* build/log/* && make CPUS=4 V=1 BOARD=t420-maximized || touch /tmp/failed_build
           no_output_timeout: 3h
       - run:
           name: Output build failing logs
           command: |
             if [[ -f /tmp/failed_build ]]; then find ./build/ -name "*.log" -type f -mmin -1|while read log; do echo ""; echo '==>' "$log" '<=='; echo ""; cat $log;done; exit 1;else echo "Not failing. Continuing..."; fi
       - run:
-          name: Output t420-external-flash hashes
+          name: Output t420-maximized hashes
           command: |
-            cat build/t420-external-flash/hashes.txt \
+            cat build/t420-maximized/hashes.txt \
       - run:
-          name: Archiving build logs for t420-external-flash
+          name: Archiving build logs for t420-maximized
           command: |
-            tar zcvf build/t420-external-flash/logs.tar.gz ./build/log/*
+            tar zcvf build/t420-maximized/logs.tar.gz ./build/log/*
       - store-artifacts:
-          path: build/t420-external-flash
+          path: build/t420-maximized
 
       - run:
           name: qemu-coreboot
